### ISSUE TITLE
Spacing between paragraphs feels too tight

### ISSUE THREAD

**Issue by nottrobin** [canonical/vanilla-framework#1993]
The spacing between paragraphs feels really cramped when compared to the other spacing around headings, rows etc. E.g.:

![image](https://user-images.githubusercontent.com/519935/45671364-91da7f80-bb25-11e8-8fa2-9c969a121835.png)

**Comment by nottrobin** [comment]
@degville was interested in this

**Comment by deadlight** [comment]
@nottrobin If you have worked around this in a particular project, can you raise your solution as a proposal so that we can discuss it in the next Working Group meeting, please?

**Comment by nottrobin** [comment]
@deadlight I haven't. I was hoping to change the system from within.

**Comment by kwm14** [comment]
As discussed with @lyubomir-popov in Design review.

**Comment by lyubomir-popov** [comment]
https://github.com/vanilla-framework/vanilla-framework/pull/2117 addresses this.
