### ISSUE TITLE
Extend has-icon

### ISSUE THREAD

**Issue by anthonydillon** [canonical/vanilla-framework#3102]
## Pattern to amend
buttons `.has-icon`

## Visual
![image](https://user-images.githubusercontent.com/1413534/83149569-287c8380-a0f2-11ea-878f-2620ebfae0c7.png)

## Context
In JAAS we need to add a small amount of padding between an icon and following text. It would be nice to be able to use a `has-icon` style utility.

**Comment by bartaz** [comment]
@anthonydillon What's wrong with default icon spacing when inline with text?

<img width="147" alt="Screenshot 2020-05-29 at 07 17 22" src="https://user-images.githubusercontent.com/83575/83223949-835abd00-a17c-11ea-9a00-43e528f7d963.png">

https://codepen.io/bartoszopka/pen/RwWzejO

You need smaller padding? Bigger? You don't want to put space between text and icon?

Is this supposed to be on a button/buttons? or simply an utility to put on text elements?

**Comment by anthonydillon** [comment]
It seems hacky and not easy to control to depend on whitespace to provide space instead of margin or padding.

**Comment by lyubomir-popov** [comment]
The values should be .5rem between icon and the text associated with it, and 1rem (or more) between unrelated pairs, at least that's what we [specced out for the table](https://discourse.ubuntu.com/t/icon-positioning-within-tables/14435).

Having something like `<span class="has-icon">[] text</span>` sounds quite useful to me too.

**Comment by lyubomir-popov** [comment]
given the need to apply .5/1rem depending on whether something is related or not, should it cover text and icons only? or also things like this from jujucharms:

![image](https://user-images.githubusercontent.com/2741678/83255417-486e7e80-a1a8-11ea-90e4-43104add60e7.png)

**Comment by anthonydillon** [comment]
Here is my local fix for reference:
https://github.com/canonical-web-and-design/jaas-dashboard/blob/dea14e36e0209797e10dc02111ede703c87a96c9/src/scss/_utils.scss#L35-L40

**Comment by bartaz** [comment]
I guess it should be treated as a utility, so we would name it `.u-has-icon` (?)
