### ISSUE TITLE
Website vitals to hit thresholds

### ISSUE THREAD

**Issue by anthonydillon** [canonical/vanilla-framework#3159]
I would like to challenge the framework to improve the vitals to be all green:
![image](https://user-images.githubusercontent.com/1413534/86920869-3de9c200-c122-11ea-8b7b-18d5bbdec578.png)

**Comment by bartaz** [comment]
Any details on where it's measured and with what tool?

**Comment by anthonydillon** [comment]
I used https://web.dev/measure/ and targetted the homepage: https://vanillaframework.io/

**Comment by lyubomir-popov** [comment]
I get somewhat different numbers - this test might be a shifting target?

![image](https://user-images.githubusercontent.com/2741678/87017813-60361b00-c1c8-11ea-8139-3768d3e16f2e.png)

**Comment by bartaz** [comment]
I think results differ for https:// and http://

Numbers aside, they give couple specific issues that may be worth looking into:

<img width="992" alt="Screenshot 2020-07-09 at 14 44 11" src="https://user-images.githubusercontent.com/83575/87041634-cb94e280-c1f2-11ea-93b4-c8eb91187ade.png">

**Comment by bartaz** [comment]
Seems all green now!

<img width="979" alt="image" src="https://user-images.githubusercontent.com/83575/236179066-160dfa7e-a9d8-4e26-b40e-d87486e5265c.png">
