### ISSUE TITLE
Slider component isn't spaced correctly + looks strange with number input type.

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical/vanilla-framework#3163]
**Describe the bug**

The slider component doesn't follow the standard Vanilla form field spacing. The input is also slightly larger than normal. It also looks misaligned when using input `type="number"` because of the browser arrows.

**To Reproduce**

1. Go to https://vanillaframework.io/docs/examples/patterns/slider/slider-input
2. The inputs have 0 margin underneath them, unlike other form fields
3. Change the `p-slider__input` to `type="number"`
4. Number should now be slightly misaligned

**Expected behavior**

Consistent alignment with other Vanilla form fields + non-wonky number input

**Screenshots**

![2020-07-10_14-50](https://user-images.githubusercontent.com/25733845/87118351-80e09c80-c2be-11ea-881f-32e3f7e01550.png)

**Comment by huwshimi** [comment]
I'll put up a PR to fix the height, but I can't seem to reproduce the misalignment when using a number input.

Chrome:

<img width="105" alt="Screen Shot 2022-10-11 at 12 53 27 pm" src="https://user-images.githubusercontent.com/361637/194979721-0bf263c3-6144-48a9-b354-3ca2c84a3425.png">


Firefox:

<img width="109" alt="Screen Shot 2022-10-11 at 12 53 18 pm" src="https://user-images.githubusercontent.com/361637/194979739-333c59be-4d81-4103-aee6-2af192a473f1.png">

**Comment by huwshimi** [comment]
Ah, I can reproduce this in Chrome when not in responsive mode:

<img width="126" alt="Screen Shot 2022-10-11 at 1 10 07 pm" src="https://user-images.githubusercontent.com/361637/194981468-b0347260-5dd8-473c-94d9-7d18489cb0eb.png">

It looks like the only way to fix this would be to make the spin buttons always or never visible. I guess always visible would be the more accessible, but not sure if that's the right approach. Any ideas?
