### ISSUE TITLE
Document theme colours

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#3301]
We have a bunch of [theme colours ](https://github.com/canonical-web-and-design/vanilla-framework/blob/6c10be5ad0dda14128521db492f3865a7aae6f30/scss/_settings_colors.scss#L50) that have not been added to the [documentation](https://vanillaframework.io/docs/settings/color-settings), we need to update to explain when/how to use the theme colours.

**Comment by bartaz** [comment]
We have this tracked as part of migrating to new theming in JIRA: https://warthogs.atlassian.net/browse/WD-7593

Closing this as duplicate.
