### ISSUE TITLE
p-heading-icon--medium and p-heading-icon--large

### ISSUE THREAD

**Issue by albertkol** [canonical/vanilla-framework#3376]
This is about https://vanillaframework.io/docs/patterns/heading-icon

Currently we offer only `p-heading-icon--small` which sets the size of the icon to `2rem`. 

I want the icon to be 4rem and it would be nice if we would have `p-heading-icon--medium` or `p-heading-icon--large` to achieve that.

Having `p-heading-icon--small` implies the existence of at least `p-heading-icon--large`, it was heartbreaking to find out that there is no such thing. </3 

Reference to the PR with the local change: https://github.com/canonical-web-and-design/ubuntu.com/pull/8520

**Comment by lyubomir-popov** [comment]
Agreed in working group to fix heading sizes and provide an additional icon size foer a larger heading

- h3, h4 (currently present), with set icons for them
- h1 to be added, icon to be balanced against that font size (and responsively change to stay balanced as the size of the heading changes between breakpoints)
- one size per heading (one that looks well next to h1, one that looks well next to h3, one that looks well next to h4), we do not try and compensate for icon visual weight

- Include guidance for icon designer on what adjustments might be needed for different icon sizes.

**Comment by lyubomir-popov** [comment]
Related issue https://github.com/canonical-web-and-design/vanilla-framework/issues/2505

**Comment by bartaz** [comment]
Likely it will involve 2 separate tasks:

#### Make heading icon define both icon size and heading size

Update existing heading icon pattern (both default and `--small` variant) to set the size of the `p-heading-icon__title` element regardless of it's HTML tag.

- default variant should set `__title` to use same font as h3, with consistent icon size
- `--small` variant should set `__title` to use same font as h4, with consistent smaller icon size

#### Add large variant to heading icon

Add `--large` variant to the pattern that would set the `__title` font size to be same as h1 with consistent large icon (see ubuntu takeovers for reference).

**Comment by clagom** [comment]
Related to #3061

**Comment by clagom** [comment]
Blocked for this cycle as the issue requires internal product audit and clean-up.

**Comment by clagom** [comment]
WG: @lyubomir-popov  to have a look at the visual spec and talk with devs for the implementation

**Comment by clagom** [comment]
@lyubomir-popov to have a look at this issue during the iteration

**Comment by lyubomir-popov** [comment]
I would propose the following:
48px (3rem) icon on desktop, 40px (2.5rem) icon on smaller screens to match the smaller heading size at those resolutions.


<img width="1163" alt="image" src="https://user-images.githubusercontent.com/2741678/175008691-61a1cfdb-5d0d-4073-ab77-2d71b3dd4311.png">

**Comment by bartaz** [comment]
This was designed but never implemented.

**Comment by bartaz** [comment]
@lyubomir-popov This is quite an old one. Do you think it's still relevant with the new rebranding? How should heading icon component work with the new heading typography - do we still need the large icon version proposed here?

**Comment by bartaz** [comment]
Lyubo: this is a component we should deprecate and have a way to insert an icon in chosen places.
Adrian: for new architecture we need to have best practices to include icons with text

Decision: dropped

**Comment by albertkol** [comment]
I've been eagerly waiting for **4 years** for this! 

> Decision: dropped

#Disappoint #CanoniUncool
