### ISSUE TITLE
New pagination pattern being used

### ISSUE THREAD

**Issue by anthonydillon** [canonical/vanilla-framework#3649]
## Pattern to amend
Pagination

## Visual
![image](https://user-images.githubusercontent.com/1413534/112269409-3e09fd80-8c70-11eb-9c63-8339c8fb5c85.png)

## Context
This new style of next and previous pagination is being placed at the top of tables in MAAS.

**Comment by anthonydillon** [comment]
It's similar to [the existing pattern](https://vanillaframework.io/docs/patterns/pagination#previous--next-buttons-only) just without text or space between the buttons.

**Comment by clagom** [comment]
Discussed during the WG, Lyubo is gonig to work on the new visual and amend the component.

**Comment by bartaz** [comment]
New pagination is being discussed separately in https://github.com/canonical/vanilla-framework/issues/4704
