### ISSUE TITLE
l-fluid-breakout has no max width

### ISSUE THREAD

**Issue by solazio** [canonical/vanilla-framework#3723]
## Pattern to amend

l-fluid-breakout

## Visual

![image](https://user-images.githubusercontent.com/40214246/116423219-65885300-a838-11eb-8cd7-8870d1ea2c47.png)

## Context

We should handle the width of the cards in a way.

I did a fix adding a `max-width`, which works fine with one card, however if you have 2 or 3 (and depending on the screen size) you will get odd spacing.

https://charmhub.io/?q=mattermost

**Comment by bartaz** [comment]
Seems to still be an issue.

**Comment by bartaz** [comment]
Triaging: effort low, impact low.

@lyubomir-popov Is this layout still supported and needed? Do we want to migrate it to new architecture? 

Needs team decision.

**Comment by lyubomir-popov** [comment]
Don't  think we need to do this, low impact, unclear whether still needed
