### ISSUE TITLE
Pullquote component uses incorrect variables and arbitrary hardcoded values

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#3821]
The pull quote padding-left in particular multipies an existing variable by an arbitrary amount. This is so the quotaiton mark fits. The problem wiht that is, if the value of the variable changes, so will he padding here, which wouldn't be intended - as the font-size of the quotaiton mark hasn't changed.

A better way to do this would be to measure the size of the quotation mark in a unit relative to its font-size (i.e. em), then sum that with a spacing variable like $sph-inner.
![image](https://user-images.githubusercontent.com/2741678/123770720-67b37000-d8c2-11eb-8456-aee58ed9b8d6.png)

![image](https://user-images.githubusercontent.com/2741678/123763697-f670be80-d8bb-11eb-9cca-9b211a02096a.png)

**Comment by bartaz** [comment]
Triaging: this was either partially addressed by now, or not worth addressing before moving to new architecture.
