### ISSUE TITLE
Request for a heading link for anchor sharing

### ISSUE THREAD

**Issue by anthonydillon** [canonical/vanilla-framework#3863]
We would like to add anchor links to headings in docs. This would need some styling. This could be in the form of a icon on hover.

**Comment by bartaz** [comment]
On GH:

![anchor.gif](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/826c0c2c-d865-4391-b48b-d3edc1b84b88)

**Comment by clagom** [comment]
To be planned for later iterations

**Comment by bethcollins92** [comment]
I'm currently working on this [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/4195). For now I'm going to make sure the header links are hidden apart from on hover, but they need new styling.

**Comment by bartaz** [comment]
Bringing it back to live. How do we move it forward. Does it need any UX? Just visual design?

**Comment by bartaz** [comment]
Fixed in https://github.com/canonical/vanilla-framework/pull/5120
