### ISSUE TITLE
Remove hardcoded values from search and filter component

### ISSUE THREAD

**Issue by sowasred2012** [canonical/vanilla-framework#3868]
The search and filter pattern uses a number of hardcoded values for things like padding, positioning, negative margins etc, and it's not clear why those values were chosen or how the pattern would be affected by changes to global spacing variables.

Replacing them with variables either defined locally or whose values are derived from other spacing variables would make them less fragile.

**Comment by bartaz** [comment]
Triaging: it's either already addressed, or not worth addressing in current v4 codebase. Component will be later migrated to new architecture.
