### ISSUE TITLE
Search and filter search prompt should match the contextual menu dropdown

### ISSUE THREAD

**Issue by sowasred2012** [canonical/vanilla-framework#3869]
The search and filter search prompt is currently very spacious, and includes padding at the top that makes it look as though it has a thick, white top border:

![Screenshot from 2021-07-14 10-32-59.png](https://images.zenhubusercontent.com/5cd93aaf2406d87914830598/ef7879c8-2672-4d2e-868e-1f1f16cda6f2)

We should make this search prompt look similar to the contextual menu dropdown (without the fixed width):

![Screenshot from 2021-07-14 10-33-09.png](https://images.zenhubusercontent.com/5cd93aaf2406d87914830598/1a3bd0a0-4211-4c04-910b-bb5d5f298940)

**Comment by cristinadresch** [comment]
@ziheliu214 @lyubomir-popov could you review this and check you're happy with this change?

**Comment by ziheliu214** [comment]
@sowasred2012 My intention was to keep the search prompt spacious to differentiate with the categories and items below in the menu. Noticed the white border - the grey background was supposed to be a hover state, but now it seems to be always there and not alined with the menu border. 

So I guess the solution can be, to make the menu upper boarder lower to the grey area, or remove the grey and put hover state on the search pompt instead.

@lyubomir-popov What do you think?

**Comment by lyubomir-popov** [comment]
@ziheliu214 @sowasred2012 I agree the gray should be a hover state. the height of the area highlighted by the grey hover should be consistent with other similar elements like the contextual menu and side navigation. No need for the top sliver of white if it can be avoided.

**Comment by lyubomir-popov** [comment]
@sowasred2012 this should be ready for development. Let me know if you need anything.

**Comment by bartaz** [comment]
This was (partially) addressed with new theming. Not relevant anymore.
