### ISSUE TITLE
Update List Tree visual design with chevrons

### ISSUE THREAD

**Issue by elioqoshi** [canonical/vanilla-framework#3994]
Based on https://github.com/canonical-web-and-design/vanilla-squad/issues/968#issuecomment-823104390 we should update the visuals for list trees as well. They are currently using + and -:

https://vanillaframework.io/docs/patterns/list-tree

![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/e38b5585-1bf5-41bf-af30-4b8755ddf8b0)

**Comment by clagom** [comment]
WG: moving to dev and eventually QA design wise

**Comment by bartaz** [comment]
Done: https://github.com/canonical/vanilla-framework/pull/5270
