### ISSUE TITLE
Investigate ways to add helper JS scripts/modules to Vanilla

### ISSUE THREAD

**Issue by sowasred2012** [canonical/vanilla-framework#4002]
Vanilla has an increasing number of patterns that require Javascript to work (Modal, content tabs, the upcoming search in the navigation etc) - it would be nice to figure out a way to make it easier for Vanilla users to add that functionality, without them needing to manually copy the same code from project to project.

**Comment by bartaz** [comment]
Tracked in [WD-240](https://warthogs.atlassian.net/browse/WD-240)
