### ISSUE TITLE
[Accessibility Docs] Breadcrumbs

### ISSUE THREAD

**Issue by sowasred2012** [canonical/vanilla-framework#4038]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Breadcrumbs](https://vanillaframework.io/docs/patterns/breadcrumbs)

**Comment by bethcollins92** [comment]
Notes are up here: https://vanillaframework.io/docs/patterns/breadcrumbs#accessibility
