### ISSUE TITLE
[Accessibility Docs] Matrix

### ISSUE THREAD

**Issue by sowasred2012** [canonical/vanilla-framework#4053]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Matrix](https://vanillframework.io/docs/patterns/matrix)

**Comment by bartaz** [comment]
Triaging: High effort (docs don't exist), impacts accessibility (documentation only).
Should be addressed in next architecture docs. Not doing as part of v4.

**Comment by bartaz** [comment]
Matrix is being deprecated. No need to do it at all.
