### ISSUE TITLE
[Accessibility Docs] Quotes

### ISSUE THREAD

**Issue by sowasred2012** [canonical/vanilla-framework#4060]
Using [this template](https://docs.google.com/document/d/1IwFMfJrTfJPXDcVJfLWXYkw-pjgWhBWo4GX8X098Q64/edit#), create accessibility docs for [Quotes](https://vanillframework.io/docs/patterns/pull-quote)

**Comment by bethcollins92** [comment]
[Accessibility doc](https://docs.google.com/document/d/1pRncWWbbpJtQSM-pQ-YFeKw8hNdxErFOzCtiISjTbRc/edit#) for now, but it's blocked by this [issue](https://github.com/canonical-web-and-design/vanilla-framework/issues/4263)

**Comment by bethcollins92** [comment]
The issue is now fixed, so the doc is ready to be reviewed and added to the site
