### ISSUE TITLE
Side navigation collapse/expand sections - build

### ISSUE THREAD

**Issue by bartaz** [canonical/vanilla-framework#4122]
UX design issue:
https://github.com/canonical-web-and-design/vanilla-framework/issues/3817#issuecomment-893271621

Visual design issue:
https://github.com/canonical-web-and-design/vanilla-framework/issues/3908

**Comment by bartaz** [comment]
This was implemented separately.

**Comment by bethcollins92** [comment]
Haven't seen your face in my GitHub notifications for a while @bartaz 😄

**Comment by bartaz** [comment]
> Haven't seen your face in my GitHub notifications for a while @bartaz 😄

I can mention you @bethcollins92 in some issues from time to time if that would brighten your day 😄
