### ISSUE TITLE
list component - Figma library

### ISSUE THREAD

**Issue by long-chung** [canonical/vanilla-framework#4153]

**Comment by long-chung** [comment]
Ready for review. (My last PR 🥺😭)

I haven't grouped these in to one big group because there are so many different types of lists with their own parameters. So i'll leave it up to you folks to work out the best course of action on how these should/shouldn't be grouped.

Thanks.

**Comment by elioqoshi** [comment]
Thanks so much @long-chung! @lyubomir-popov and me will probably go over this next week to see what's the best approach to take.

**Comment by elioqoshi** [comment]
@lyubomir-popov structure I am suggesting:

![image.png](https://images.zenhubusercontent.com/5a5649f54b5806bc2bc23b6d/ed4e0a26-4619-4baa-925b-9f552da0aff9)

**Comment by bartaz** [comment]
Figma library is handled outside of our backlog now.
