### ISSUE TITLE
Default fixed max-width on ul/ol

### ISSUE THREAD

**Issue by bethcollins92** [canonical/vanilla-framework#4161]
## Pattern to amend

- ul/ol
- See Lyubo's [comment](https://github.com/canonical-web-and-design/vanilla-framework/pull/4160#issuecomment-982430976) about adding the `$text-max-width` as default to lists
- Can we try and see if anything breaks setting the max width on lists as default? This will ensure the text in lists always wraps the same as paragraphs but could potentially break lists containing other elements e.g nav and footer

**Comment by anthonydillon** [comment]
@bethcollins92 this one needs an estimate.

**Comment by bethcollins92** [comment]
This needs to be discussed again after the release of Vanilla 3.0 so put this issue in icebox

**Comment by bartaz** [comment]
hey @bethcollins92 :)

In the meantime this has been fixed by new utility: https://vanillaframework.io/docs/utilities/text-max-width
