### ISSUE TITLE
Side navigation component - Figma Library

### ISSUE THREAD

**Issue by marinacastejon** [canonical/vanilla-framework#4213]
The side navigation component is not totally ready for use (unless it was done as it is on purpose with a good reason?): 
- The menu items do not have fixed width. This is an issue in figma when we have long names that need to be wrapped. 

- The naming of the menu items are inconsistent with Vanilla. My understanding is that the hover state changes color but does not display the side vertical line, which is the case in figma. 
![image.png](https://images.zenhubusercontent.com/61309e789df65d8124887eac/e5839be4-7de9-4416-99db-a086de6e20bb)
In Vanilla this corresponds to the active state.
![image.png](https://images.zenhubusercontent.com/61309e789df65d8124887eac/8fac57c4-74c5-4cae-a9e3-d1680e551c51)

There might be other things to check in addition to this.

**Comment by bartaz** [comment]
Figma library is handled outside of our backlog now.
