### ISSUE TITLE
[Document Design System] Write component/pattern accessibility docs

### ISSUE THREAD

**Issue by bethcollins92** [canonical/vanilla-framework#4281]
From https://github.com/canonical-web-and-design/vanilla-squad/issues/1100:

> for Dev, to add accessibility content in each component's implementation spec, including
> - "How it works" explaining why aria attributes etc are important for accessibility
> - "accessibility consideration" about how a developer should consider accessibility when using this component
> - "Resources" (or reference) from W3C, WCAG and WebAIM, etc

**Comment by bartaz** [comment]
Closing, this is an old epic from ZenHub.
