### ISSUE TITLE
Data Visualisation

### ISSUE THREAD

**Issue by AnnSoMuller** [canonical/vanilla-framework#4303]
This is the Epic around the Data Visualisation work.
Here is the [Miro Board](https://miro.com/app/board/uXjVOcXQvUc=/?moveToWidget=3458764514847626108&cot=14) for the working group research quick start.
Here is the [Drive folder](https://drive.google.com/drive/folders/1I0jmf_SSVBgvBf3UmbHdUERARlyszC6y?usp=sharing) with different docs.

**Comment by cristinadresch** [comment]
Created a phase 2 epic here https://app.zenhub.com/workspaces/-design-system-tribe-59438c953747487777fbe484/issues/canonical-web-and-design/vanilla-squad/1237
