### ISSUE TITLE
All columns full width in the default example in docs

### ISSUE THREAD

**Issue by huwshimi** [canonical/vanilla-framework#4354]
**Describe the bug**

The columns in the "Grid / Default" example in the docs are all full width.

**To Reproduce**

1. Go to https://vanillaframework.io/docs/patterns/grid
2. Scroll down to the "Grid / Default" example
3. See that all the columns are the full width of the container.

**Expected behavior**

I expected the columns to be the size defined by their class.

**Screenshots**

<img width="855" alt="Screen Shot 2022-03-08 at 1 09 00 pm" src="https://user-images.githubusercontent.com/361637/157152423-71686603-7d2a-4762-9849-16fe89b35d2c.png">

**Comment by bartaz** [comment]
Doesn't happen anymore with new layout.
