### ISSUE TITLE
Review segmented control specs with current template

### ISSUE THREAD

**Issue by danielmutis** [canonical/vanilla-framework#4419]

**Comment by danielmutis** [comment]
Note to self: remove the benchmarking section

**Comment by lyubomir-popov** [comment]
@danielmutis Does this need to be in UI/UX? Sounds like a reformatting job rather than something that requires UI/UX discusssion.

**Comment by bartaz** [comment]
@danielmutis Is this still relevant or is this a piece of some old work?
