### ISSUE TITLE
p-divider__block doesn't handle responsive columns.

### ISSUE THREAD

**Issue by huwshimi** [canonical/vanilla-framework#4438]
**Describe the bug**

When using p-divider__block with responsive columns (e.g. `col-medium-...`) the dividers move to horizontal before the columns.

**To Reproduce**

1. Go to https://codepen.io/huwshimi/pen/VwyJjVY
2. Resize your window down to medium size.
3. See that the columns are still horizontal but the borders move to the top.
4. Resize down to mobile and the columns and borders are back to looking correct.

**Expected behavior**

The borders should stay horizontal.

**Screenshots**

The border is correct at large size:

<img width="1173" alt="Screen Shot 2022-04-26 at 11 27 35 am" src="https://user-images.githubusercontent.com/361637/165201214-7c8d282d-4886-4cfc-a295-700e0e3eb231.png">

Changing to medium the borders move to the top but because of the `col-medium-...` classes the columns stay where they were:

<img width="894" alt="Screen Shot 2022-04-26 at 11 27 43 am" src="https://user-images.githubusercontent.com/361637/165201221-22674cdc-0740-49bb-9639-f480bdae2e69.png">

At mobile size all's right in the world again:

<img width="575" alt="Screen Shot 2022-04-26 at 11 28 22 am" src="https://user-images.githubusercontent.com/361637/165201226-a03910f8-2c87-48a8-bef1-78a61f4281eb.png">

**Additional context**

This might require additional classes to correctly set the borders at each size, but at the moment (as far as I can see) there isn't a way to fix this without a custom implementation of `p-divider__block`.

**Comment by bartaz** [comment]
I don't think it was intended to support mobile columns, just a predefined layout.

But I agree that the fact that it uses grid class names directly suggest any other grid class names can be used (including responsive). 
We need to take a look if that's something we can fix (make it work with any grid columns), or we have to limit it to one predefined layout.
