### ISSUE TITLE
Side navigation with drawer explicitly sets background color to white

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical/vanilla-framework#4458]
**Describe the bug**

When using the side navigation pattern with the slide out drawer the full-screen version has a white background, which looks weird when the page background is a different colour.

**Expected behavior**

Either the side nav background is transparent or there is a way to set the colour.

**Screenshots**

![Screenshot 2022-05-09 at 15-33-14 General bolla MAAS](https://user-images.githubusercontent.com/25733845/167346572-c5a0b691-2dac-462e-86e9-98486830cba9.png)

**Comment by huwshimi** [comment]
I wasn't quite sure what the right approach for this is. At the moment `$color-sidenav-background-default` is used for both the in-page and drawer versions of the menu.

If we don't set the background colour for the in-page menu then you won't be able to theme it when used in-page.
We could say that you have to use `$color-sidenav-background-default` to match the background colour for the in-page version but then they would also get that colour when viewing the drawer.

We could introduce drawer and in-page specific background variables but that would have knock on effects so we'd probably have to have a full set of variables for in-page/drawer.

I guess one other way would be to have a modifier class to remove the background when viewing the in-page version, but that doesn't seem the most elegant...

Any ideas?

**Comment by huwshimi** [comment]
@bartaz taking another look at whether we can just remove the background, I ran into issues with the dark examples: https://vanillaframework.io/docs/examples/patterns/side-navigation/dark.

I'm not sure if the background colour of the page and the middle blue example are real world cases, but with no changes the left and right examples have a lighter background than the page:

<img width="1037" alt="Screen Shot 2022-10-12 at 10 24 26 am" src="https://user-images.githubusercontent.com/361637/195216663-81f8e2b9-e8c4-4346-bf8d-57a3c737514b.png">

But if I set it to remove the background the left and right examples lose their lighter background and the middle example loses its blue background:

<img width="1037" alt="Screen Shot 2022-10-12 at 10 25 09 am" src="https://user-images.githubusercontent.com/361637/195216755-cf745de9-3f88-4a3a-87ab-7e4f96f9f255.png">

**Comment by bartaz** [comment]
@huwshimi Yes, seems its trickier than expected.

But, in the examples we actually show how to override the color (you need to set inline CSS on the drawer element `p-side-navigation__drawer` and the header `p-side-navigation__drawer-header` inside it.
Would that be enough for you to get the gray backtround in MAAS?

**Comment by huwshimi** [comment]
> @huwshimi Yes, seems its trickier than expected.
> 
> But, in the examples we actually show how to override the color (you need to set inline CSS on the drawer element `p-side-navigation__drawer` and the header `p-side-navigation__drawer-header` inside it. Would that be enough for you to get the gray backtround in MAAS?

It looks like the background colour has been [overridden for large screens](https://github.com/canonical/maas-ui/blob/main/src/scss/_vanilla-overrides.scss#L26):

```scss
.p-side-navigation .p-side-navigation__drawer {
  @media screen and (min-width: $breakpoint-large) {
    background-color: transparent;
  }
}
```

Maybe it's acceptable to just leave it as it is then?

**Comment by bartaz** [comment]
@huwshimi Yes, seems fine for now. We may revisit it later if it causes similar issues in other places.

**Comment by bartaz** [comment]
Closing this for now. Background can be overridden locally in projects if needed.
