### ISSUE TITLE
Sticky table of contents

### ISSUE THREAD

**Issue by carkod** [canonical/vanilla-framework#4488]
## Pattern to amend

Sticky option for [Table of contents pattern](https://vanillaframework.io/docs/patterns/table-of-contents)

## Visual

The privacy page of u.com already has an implementation. Open the link and scroll to see the effect
https://ubuntu.com/legal/data-privacy

## Context

In what context does your amendment solve a problem?

**Comment by clagom** [comment]
Thanks @carkod - @danielmutis is going to include this proposal within the work for the table of content component itself.
