### ISSUE TITLE
New nav logo padding does not align with content

### ISSUE THREAD

**Issue by sowasred2012** [canonical/vanilla-framework#4530]
**Describe the bug**

_First reported as an issue on https://github.com/canonical/design.ubuntu.com/issues/241_

The new "tag" logo is not correctly left aligned with the content below, it seems to be .5rem off.

**To Reproduce**

Visit https://dqlite-io-209.demos.haus/ or https://design.ubuntu.com/, see that the "tag" logo style does not align on the left hand side with the content below at widths greater than 620px.

**Expected behavior**

The nav logo and content should be aligned

**Screenshots**

![Peek 2022-08-04 23-53](https://user-images.githubusercontent.com/2376968/182968688-dc2b8bf0-5ddc-442b-ba59-ae36435e6ebf.gif)

**Comment by bartaz** [comment]
Let's fix it outside of the blocked logo work.
