### ISSUE TITLE
issue with global_functions?

### ISSUE THREAD

**Issue by alfred-tuinman** [canonical/vanilla-framework#4534]
I install the software via npm and import vanilla as suggested but I get an error on line 86 of node_modules/vanilla-framework/scss/_global_functions.scss:

"invalid css after "     $value: math": expected "}", was ".div($value, $n..."

I use Ubuntu 22.04

![Screenshot from 2022-08-14 10-36-51](https://user-images.githubusercontent.com/110611318/184523373-478b7a90-7163-402a-bec0-f8693a832683.png)

**Comment by bartaz** [comment]
Hey @alfred-tuinman can you give us more details on how you import and build Vanilla?

What are you using for building, is it `sass` npm package?

**Comment by bartaz** [comment]
I will close this for now as we can't reproduce it without more context, but feel free to reopen if needed. Thanks!
