### ISSUE TITLE
Offscreen component leaves thin white line in Firefox

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/vanilla-framework#4535]
**Describe the bug**

1px high white line appears for supposedly offscreen tooltip when scrolling down past the content on Firefox.

**To Reproduce**

1. Go to a MAAS install tracking edge e.g. [bolla.internal:5240/](http://bolla.internal:5240/MAAS/r/devices)
2. Scroll down the main viewport to attempt to get off-screen
4. See thin white line appear at the bottom of the screen

**Expected behavior**

No thin white line.

**Screenshots**

![image](https://user-images.githubusercontent.com/246192/184627075-b847885a-a965-4c24-902c-900999210418.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04
- Browser Firefox
- Version 103.0.2

**Additional context**
If I disable the `height` rule in devtools from 

```
.u-off-screen {
    height: 1px !important;
    left: -10000px !important;
    overflow: hidden !important;
    position: absolute !important;
    top: auto !important;
    width: 1px !important;
}
```

AKA https://github.com/canonical/vanilla-framework/blob/13e133cfeef3088db484aad25ab078e70c65f902/scss/_utilities_off-screen.scss#L6

then the bug goes away.

**Comment by petermakowski** [comment]
I tested `.u-off-screen` when used for visually hidden form element labels (e.g. search box in MAAS UI). Removing the fixed `1px` height has no effect on the assistive technology's ability to announce its contents. Everything works as expected.

Should be good to remove from the a11y standpoint, unless you can think of any other use case for this @bartaz ?
