### ISSUE TITLE
need h2 counters

### ISSUE THREAD

**Issue by minkyngkm** [canonical/vanilla-framework#4558]
l**Describe the bug**

<img width="231" alt="image" src="https://user-images.githubusercontent.com/57550290/186927549-bcaec1de-755c-445d-b0a5-545c01f306b9.png">

![image](https://user-images.githubusercontent.com/57550290/186925283-0908f517-571f-4c97-91a8-49fd0819066f.png)

after updating vanilla 3.7, the counters are not elliptical any more but it doesn't look perfectly good. 

@lyubomir-popov mentioned vanilla doesn't seem to have h2 counters.

**Comment by bartaz** [comment]
@minkyngkm Thanks for the report.

Could you give us more details on what is broken?
Do you have any custom styles on top of Vanilla - I don't think we have black circle, or circles with borders in stepped list.

**Comment by lyubomir-popov** [comment]
I think the small imperfections above are due to local styles clashing with the vanilla styling, as they are not present in the official vanilla example. Closing this.
