### ISSUE TITLE
Stepped lists: Change counter font-size to root font size

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4561]
## Pattern to amend

Proposal: 
1) make counters (numbers in circles) paragraph size, regardless of the heading style of the titles
2) replace gray-filled circles with ones that are white with a black outline. This way it will be consistent with the new stepper designs

Counter circles become too large and prominent when they contain a digit in the same size as the heading: 

![image](https://user-images.githubusercontent.com/57550290/186925283-0908f517-571f-4c97-91a8-49fd0819066f.png)

Can we instead stick to paragraph size like so:

## Visual

![image](https://user-images.githubusercontent.com/2741678/187672881-9729a793-f363-486d-95b5-edf2612bb3ac.png)

**Comment by bartaz** [comment]
@lyubomir-popov as purely visual update - can it go straight for development, or do you want it discussed/reviewed first?

**Comment by lyubomir-popov** [comment]
I would say straight to development. I don't think a minor detail like this is requires extensive debate.

**Comment by huwshimi** [comment]
Just wanted to confirm a couple of things:

The size of the counters will be fixed to the base line height size (with the text set to the base font size)?

The font-weight will be set to the regular text weight (300) ignoring the title's font weight?

Something like this:

<img width="760" alt="Screen Shot 2022-10-11 at 12 25 06 pm" src="https://user-images.githubusercontent.com/361637/194976969-c136d4c5-136c-4c9b-92b1-6c317514b964.png">

**Comment by bartaz** [comment]
@lyubomir-popov Can you have a look at Huw's questions about it - it's a bit unclear what we want to achieve here.

**Comment by lyubomir-popov** [comment]
@huwshimi I had to quickly hack it together in one place, here's what I did 

```
        &::before {
          font-size: 1rem;
          font-weight: 500;
          line-height: 2rem;
          margin-top: .6rem;
          width: 2rem !important;
        }

![image](https://user-images.githubusercontent.com/2741678/195364276-c0cbe63c-2d83-4f38-bd79-4cf0d7feb38c.png)

```

**Comment by huwshimi** [comment]
@lyubomir-popov I've pushed up a draft PR here: https://github.com/canonical/vanilla-framework/pull/4584.

I haven't updated the size yet as the base line height is `1.5rem` but in your example you've set it to `2rem` so I wasn't sure which to go with...
