### ISSUE TITLE
Lists: impossible to specify a list with both dividers and default bullets

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4569]
## Pattern to amend

We have a bulletted list:

![image](https://user-images.githubusercontent.com/2741678/193764470-e0b189ba-2520-4d5b-9fa1-557f553aa10e.png)

We also have a list with dividers:
![image](https://user-images.githubusercontent.com/2741678/193764567-394fcf18-e764-4d2a-87de-e68d66f2dd47.png)

The dividers are useful when the contents of list items are so long that individual list items start to blend into a blob of text. 
This is not immediately obvious if you look at our default bulletted list example, as it has 4 words or less per item.

Dividers can help solve that, by making individual long list items clearly separated. The presence of bullets reenforces that:

![image](https://user-images.githubusercontent.com/2741678/193765282-8b69aaad-7bb6-4bb2-910b-185d2b948ec6.png)

But the current options are dividers or bullets, not both. So my proposal is to make it possible to have both bullets and dividers.

## Context
![image](https://user-images.githubusercontent.com/2741678/193765236-bad9cc14-b50d-4b19-9de4-ee603956eee0.png)

See above. Long list items.

**Comment by lyubomir-popov** [comment]
@ClementChaumel is this still an issue

**Comment by ClementChaumel** [comment]
@lyubomir-popov this will be fixed in https://github.com/canonical/vanilla-framework/pull/4636
