### ISSUE TITLE
Lists: better align with other text

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4571]
## Pattern to amend

Lists have an indent that breaks vertical alignment with preceding text. That fulfills the goal of attracting attention, but not necessarily in a good way. 
![image](https://user-images.githubusercontent.com/2741678/193826835-fa456671-c0f7-4e8a-afb1-75a40d86d97e.png)

How about this instead:
## Visual
![image](https://user-images.githubusercontent.com/2741678/193827290-d11abdac-bedc-45c7-a621-cf1e10ed2cdb.png)
![image](https://user-images.githubusercontent.com/2741678/193827366-0712714b-dc1b-4441-8396-8882ac2da0b6.png)

Provide a screenshot or link to a prototype of your pattern amendment.

## Context

In what context does your amendment solve a problem?
Int the context of a list placed adjacent to other text content, where the discrepancy in vertical alignment becomes obvious

**Comment by lyubomir-popov** [comment]
On second thought, do we need the default list styling? Maybe the designs above could be directly applied to the base ul and ol elements.

We need to check if that will affect lists used for other things, like navigaiton for example - and make sure those override all  needed properties.

**Comment by bartaz** [comment]
@lyubomir-popov Is this still relevant? I guess new divided list style covers that?

**Comment by bartaz** [comment]
@lyubomir-popov Is this still relevant?

**Comment by bartaz** [comment]
This have been partially addressed (default list styles deprecated, use of divided list), and list spec is about to be worked on. Closing as not relevant/duplicate.
