### ISSUE TITLE
Lists have margin-collapse

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4572]
**Describe the bug**
1) Put something with a margin-bottom inside any list item:
![image](https://user-images.githubusercontent.com/2741678/194018189-8d9ab68c-559b-42a9-95d7-e1586d3a3acd.png)

2) check the heightof the list item:
![image](https://user-images.githubusercontent.com/2741678/194018244-340bd1dc-39e7-473a-bdcb-afbe38cd48e5.png)

list items need `overflow: auto;` to remedy:
![image](https://user-images.githubusercontent.com/2741678/194018546-feb32c3a-1604-499f-9729-b8baf2005e9e.png)

**Comment by bartaz** [comment]
We need to verify if "overflow: auto" doesn't break anything. Also maybe new list style covers that?

**Comment by bartaz** [comment]
We deprecated default list styles, this is likely not relevant anymore.
