### ISSUE TITLE
Component state audit and improvements

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4573]

**Comment by camillet16** [comment]
# Color state audit

### Problems
- The active state color is dependent on component size when it comes to visual weight.
- Gray is often associated with disabled components. This shows in segmented controls are limited to 2 choices.

<img width="1400" alt="Screen Shot 2022-10-07 at 10 35 32 AM" src="https://user-images.githubusercontent.com/112855834/194498366-7dbf0c0e-3b28-42ff-9821-ac597b0e7312.png">

---------

### Solutions Available
#### Solution A: Adjustment of existing color down to 7% from 10%

<img width="300" alt="Screen Shot 2022-10-07 at 10 48 37 AM" src="https://user-images.githubusercontent.com/112855834/194500854-95c60336-b5c3-43d2-b161-0f7b95340dd0.png">

#### Solution B: The color move from gray to light blue.

<img width="300" alt="Screen Shot 2022-10-07 at 10 48 44 AM" src="https://user-images.githubusercontent.com/112855834/194501074-13a2c80c-6c05-43cb-9259-31d886bf7f18.png">

---------

### Cross-comparison of solutions

<img width="902" alt="Screen Shot 2022-10-07 at 10 53 10 AM" src="https://user-images.githubusercontent.com/112855834/194501783-5d4416c8-ae9e-4a8c-83da-85c8ecfe787a.png">


###### Links
[Figma Link](https://www.figma.com/file/FDYbZCtiX8CfNMVieKvVrB/Audit?node-id=110%3A117657)

**Comment by camillet16** [comment]
### Samples:

![Screen Shot 2022-10-07 at 11 16 28 AM](https://user-images.githubusercontent.com/112855834/194506965-cb5de8e7-9103-4f1a-bde0-282932a0e506.png)
![Screen Shot 2022-10-07 at 11 14 51 AM](https://user-images.githubusercontent.com/112855834/194506968-01c294ee-3263-4d41-914c-8c42462d3445.png)
