### ISSUE TITLE
Accordion: update spec with new template

### ISSUE THREAD

**Issue by elioqoshi** [canonical/vanilla-framework#4577]
https://docs.google.com/document/d/1E0wJUKgu_5tXnmC28XPF4Cb14BpmW1XEvxbWnuC1298/edit?usp=sharing

The accordion spec has been updated according to the new template. If this is good to go we can move it over to Discourse.

**Comment by bartaz** [comment]
It's been sitting in "new issues" for a while, could we verify the status of that on WG meeting?

**Comment by elioqoshi** [comment]
IIRC this has been completed last year, I adapted it to the new templated
