### ISSUE TITLE
The grid is broken between media queries

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4592]
THere are some -1px in media queries (not sure when that got introduced) that I believe are breaking the grid. E.g.:
![image](https://user-images.githubusercontent.com/2741678/196130429-a34c72cd-200b-4efa-ab70-7d63bbd86996.png)

**Comment by bartaz** [comment]
@lyubomir-popov what is the example you are trying it with?

I think it seems to be working as expected here: https://vanillaframework.io/docs/examples/patterns/grid/responsive

<img width="716" alt="image" src="https://user-images.githubusercontent.com/83575/196138485-d6266e27-3c31-460f-9d68-c3290e81388a.png">

**Comment by lyubomir-popov** [comment]
Precisely that example^. See the cascade at +1 and -1 and then at 619 px:

![image](https://user-images.githubusercontent.com/2741678/196139317-a7b6f57c-e1a5-4963-8a0f-d04c5277d47c.png)
![image](https://user-images.githubusercontent.com/2741678/196139341-025fdc49-16e6-451e-a342-21d3a48ba6d2.png)
![image](https://user-images.githubusercontent.com/2741678/196139372-db2139ae-e38c-4b4f-89d5-c1b804e7a91f.png)

**Comment by bartaz** [comment]
For more context. This seems to be working fine on MacOS.

It seems to happen on Ubuntu and Windows (possibly may depend on the screen pixel density as well).

**Comment by mtruj013** [comment]
I'm not quite sure if I'm missing something, but I'm not able to recreate this bug on ubuntu. Both Chrome and Firefox seem to work as expected: 
![Screenshot from 2022-10-18 14-10-03](https://user-images.githubusercontent.com/17607612/196427082-da21e557-b2eb-421c-b494-1b58523ea4ce.png)
![Screenshot from 2022-10-18 14-03-01](https://user-images.githubusercontent.com/17607612/196428386-45e0e0fe-82bb-407a-a129-c5fb8c6352de.png)

**Comment by bartaz** [comment]
Seems this depends not only on OS (Ubuntu) but also on the screen/display device (pixel density?).
