### ISSUE TITLE
Refine the appearance of hover link underlines

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4600]
Can we please do the following? 
`text-decoration-thickness: 1px;
    text-underline-offset: 0.075em;`
![image](https://user-images.githubusercontent.com/2741678/196731366-70b0a642-3ff6-4c70-a761-9b4b3edf820a.png)

**Comment by larryease** [comment]
I really want to contribute to this issue but this request is not clear. can you make it more understandable, please?

**Comment by lyubomir-popov** [comment]
Hi, thanks for your interest in this. The 2 lines above simply need to be added after line 14 in this file:  https://github.com/canonical/vanilla-framework/blob/main/scss/_base_links.scss
