### ISSUE TITLE
Tooltip inside a panel is hidden

### ISSUE THREAD

**Issue by edlerd** [canonical/vanilla-framework#4607]
**Describe the bug**

Tooltip inside a panel is hidden. 

**To Reproduce**

1. Place a button with a tooltip in an application panel
3. Hover the Button
4. No tooltip is visible

**Expected behavior**

Tooltip is shown

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser Chrome
- Version 107 (latest)

**Additional context**

I think the z-index might be off. So the panel has a higher z-index than the tooltip, and as such the tooltip is not visible.

Giving the tooltip a fixed and higher z-index than the panel might create a problem: When a button with a tooltip is placed in the main component and the button opens the panel. Then the tooltip of the (now invisible, because the panel is over it) button might show on top of the panel. But maybe this situation can be avoided, and it is still a feasible solution.

**Comment by petermakowski** [comment]
I can confirm the same issue, seems like the z-index needs to be +1 of the value of the side panel z-index.
