### ISSUE TITLE
Checkboxes don’t have a hover state

### ISSUE THREAD

**Issue by fitojb** [canonical/vanilla-framework#4613]
Checkboxes don’t sligtly darken on hover, as text fields do since #4402.

**Comment by bartaz** [comment]
Thanks for the report @fitojb.

Indeed we didn't change the hover of the checkboxes or radio buttons.

I'll verify with our designers if we want to add one.

**Comment by bartaz** [comment]
@lyubomir-popov Do we want to introduce the hover state for tick elements (like we now do for text inputs)?

**Comment by lyubomir-popov** [comment]
@bartaz yes please.

**Comment by fitojb** [comment]
Fixed by #4615 — thanks!
