### ISSUE TITLE
0-gap grid row

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4614]
It would be nice to have a grid row with 0 gaps betwen the columns, to implement things like this:

## Visual

![image](https://user-images.githubusercontent.com/2741678/205611601-8e199b27-54ab-48c3-b4e5-7677cfe38eb9.png)

## Context
My idea is to put card-like padded containers (the grey boxes) with or without borders.

**Comment by bartaz** [comment]
@lyubomir-popov to make a mockup of it

we can then build a demo and see how it may work

**Comment by bartaz** [comment]
@lyubomir-popov Do you have a better mockup for that.

**Comment by lyubomir-popov** [comment]
Sorry, not yet - will need to do next iteration.

**Comment by bartaz** [comment]
@lyubomir-popov is this still something we'd like to do?

**Comment by ClementChaumel** [comment]
Let's try again next iteration! 😄

**Comment by bartaz** [comment]
Triage: this seems high effort and unknown impact. Do we really need this? If we do, consider for new architecture.

**Comment by bartaz** [comment]
@lyubomir-popov Is this still something we would like to do? Maybe as an item for new architecture (and possible revisited grid there)?
