### ISSUE TITLE
Search box pattern doesn't work with .p-form--inline

### ISSUE THREAD

**Issue by sowasred2012** [canonical/vanilla-framework#4622]
When trying to use the search box pattern with .p-form--inline, you get this, with the input somehow breaking out of the grid:
![Screenshot from 2022-12-09 15-18-38](https://user-images.githubusercontent.com/2376968/206734513-aa907fc1-0b8d-4672-a2d3-4c51384878e8.png)

But I would expect something like this (this is a standard search input, which means I lose the "Close" button the search box pattern gives):
![Screenshot from 2022-12-09 15-18-48](https://user-images.githubusercontent.com/2376968/206734522-102981ca-4427-413c-9c53-6f9602f2d36c.png)

**Comment by sowasred2012** [comment]
That was the first thing I tried:

![image](https://user-images.githubusercontent.com/2376968/206745995-e2e0d825-b995-4f9c-b1d8-db5108baa4b5.png)

So then I went looking for a Vanilla way to put a search + button inline, I found this: https://canonical.com/careers, but it looks like there's some custom styling too. It could also be I'm missing something, it's a Friday evening.

**Comment by bartaz** [comment]
@sowasred2012 Oh, I guess we don't really use searchbox + button, because searchbox has submit built-in (the looking glass icon is a button):

![image.png](https://images.zenhubusercontent.com/593a660851aa2c30578102bb/f4aff30a-0ce9-491e-8b7e-33efc675b4c8)

**Comment by bartaz** [comment]
Triage: too high effort to be addressed in v4. Forms will be revisited in new architecture.
