### ISSUE TITLE
New tiered card pattern

### ISSUE THREAD

**Issue by anthonydillon** [canonical/vanilla-framework#4640]
## Visual
![image](https://user-images.githubusercontent.com/1413534/216067895-e6ae4a82-9aae-4470-b3b5-2da6d2b55d65.png)

## Context
We have begun to use and be requested to use the new pattern from the pro page. I believe this is a card pattern and have devised a suggested pattern. `p-tiered-card`

## State
This pattern currently has a `high`, `medium` and `low` tier.

## Concerns
Should this inherit the branding of the site in some way?

**Comment by lyubomir-popov** [comment]
I would be a bit hesitant about creating a pattern out of this - it is a designb for a highly specific set of circumstances, which will likely be different  in another context. For example, if the text were 4 times longer, the number of tiers were different, the amount of features more evenly distributed (this design impleis the darker versions are more similar to each other than to the first tier), etc.
Also, the implementation is quite a bit different from the design, this pr got merged without a design approval, and I've filed an [issue ](https://github.com/canonical/ubuntu.com/issues/12473)to correct that:
![image](https://user-images.githubusercontent.com/2741678/216072127-1440de3a-1012-4961-84e8-26a49f1b0768.png)

**Comment by danielmutis** [comment]
@lyubomir-popov and @bartaz to discuss with @anthonydillon which parts of this are useful inside Vanilla. As a whole, this seems like a very specific use case which would be too narrow for it to be a component. We will look into how we can make it easier to make this happen with Vanilla.

**Comment by bartaz** [comment]
As discussed in WG and with Ant, this is currently used in 2 places on one site (ubuntu.com). And there is no direct need to componentize it.

When we need it outside of ubuntu.com we should upstream it to Vanilla at that point, only focusing on existing use cases.

Should be re-opened if needed.
