### ISSUE TITLE
.row inside .u-fixed-width leads to double side padding

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4641]
p[lacing a `.row` inside a `.u-fixed-width` container results in both elements having side padding, the inside one shouldn't:
I thought we hadfixed this a few years ago - probably a recent regression?

![image](https://user-images.githubusercontent.com/2741678/216103133-7913df7b-dad4-4ae5-9c8e-655e26492390.png)

![image](https://user-images.githubusercontent.com/2741678/216103375-2f88be66-b4fe-4d62-9b4c-318ea196fa1c.png)

**Comment by bartaz** [comment]
We have a fix for `.u-fixed-width > .u-fixed-width` and `.row > .u-fixed-width`, but not `.row > .u-fixed-width`.
