### ISSUE TITLE
Floating notifications

### ISSUE THREAD

**Issue by al-bakalova** [canonical/vanilla-framework#4645]
## Pattern to amend
Notifications 
## Visual
https://www.figma.com/file/pAjNmkq6Vou1wgkv1LJggP/LXD---Instance-management?node-id=224%3A331974&t=EqLIPDlocuryvbhE-1
## Context
Hey there! We are currently working on the LXD UI. We have lots of confirmation messages when new instances or profiles have been successfully created (or when the creation of such has failed).
To do so, we stick to the existing Vanilla pattern. In our current environment we have positioned these notifications above the table. During our user testing sessions, the participants often shared frustrations about them losing the row of the table they were browsing. 
Our solution is to offer what we call "floating notifications". The screens shared above have already been reviewed by the Visual design team and they are also happy with us introducing such element.

**Comment by bartaz** [comment]
This seems like duplicate or related to: https://github.com/canonical/vanilla-framework/issues/4494

**Comment by al-bakalova** [comment]
@bartaz Hey Bartek, my bad. Please ignore this issue. We have decided to stick to the Vanilla guidelines. 
What is more, reading Marina's arguments made us rethink the experience.
Thank you!

**Comment by bartaz** [comment]
@al-bakalova Thanks for update. This topic has been popping up recently, so I guess it may still be worth to discuss in bigger group on next Working Group where we stand on that, and what are current best practices or guidelines.

**Comment by danielmutis** [comment]
Closing it to keep track of this in this [issue](https://github.com/canonical/vanilla-framework/issues/4494).
