### ISSUE TITLE
Bug: Stepped List in dark mode didn't show numbers

### ISSUE THREAD

**Issue by shdq** [canonical/vanilla-framework#4656]
**Describe the bug**

In the dark theme stepped list numbers in circles are overwritten with white background.

<img width="334" alt="Screenshot 2023-02-14 at 12 44 16" src="https://user-images.githubusercontent.com/1219618/218684265-0cb28a2b-8b79-40c0-a653-7f960e7d41ae.png">

**To Reproduce**

Switch system setting to dark theme:

Create an empty project with the vanilla framework and add a stepped list.

**Expected behavior**

Number in white color, a circle with white border and transparent background.

<img width="331" alt="Screenshot 2023-02-14 at 12 48 34" src="https://user-images.githubusercontent.com/1219618/218685172-1372a755-ea95-4350-a68a-7a711f12b879.png">

**Possible solution**

For `.p-stepped-list__title::before` in dark mode change to `background-color` to `transparent` and `border-color` to `rgba(255, 255, 255, 0.87)`.

**Desktop (please complete the following information):**

- OS: MacOS 13.1
- Browser firefox, chrome
- Version latest

**Smartphone (please complete the following information):**

Haven't tested

**Comment by bartaz** [comment]
Thanks @shdq, indeed stepped list should have a dark theme support, or should adapt to dark background of the strip it's in.

**Comment by bartaz** [comment]
@lyubomir-popov How do we want the stepped list to look on dark backgrounds? Black circle, transparent, or something else?

**Comment by lyubomir-popov** [comment]
the circle outline matches the text colour, so it’s easy to translate that
into the dark theme
