### ISSUE TITLE
text-x-small-capitalised is inheriting the font-size from HTML

### ISSUE THREAD

**Issue by anthonydillon** [canonical/vanilla-framework#4664]
## Pattern to amend

`.p-text--x-small-capitalised`

## Visual

![image](https://user-images.githubusercontent.com/1413534/220349338-df8f4a5f-9d25-4319-8b40-1f50df9cdd3c.png)

## Context

The text--x-small-capitalised does not set the font-size or weight and so inherits these from the base styling. I believe there was a change to `@extend %vf-heading-3;` which now adds h2 styling which overrides the base styling. This pattern should set the font styles.

Seen here: https://canonical.com/careers/engineering

**Comment by bartaz** [comment]
I guess ideally these headings on engineering page should use `p-muted-heading` instead of capitalised text, but indeed the `p-text-x-small-capitalised` should set font height of it's own.

**Comment by bartaz** [comment]
Setting as high priority as this is regression in latest version of Vanilla.

**Comment by bartaz** [comment]
Fixed by #4665, not sure why it wasn't autoclosed…
