### ISSUE TITLE
Make updating the "What's new" page easier

### ISSUE THREAD

**Issue by ClementChaumel** [canonical/vanilla-framework#4666]
The current way of updating the what's new page is to manually change the version number, copy and paste the HTML from the previous version in a different place then add the changes for the new version.
![image](https://user-images.githubusercontent.com/11927929/220594802-8edab89f-c037-4d25-88db-578e10dc3be3.png)

And while it's not the end of the world, it is a bit tedious and somewhat error-prone (markup can get mangled, etc.)

We could investigate pulling all the changes from a JSON/YAML file like so:

```json
{
  "3.11.0": [
    {
      "name": "Full-width layout",
      "link": "/docs/examples/layouts/full-width/default",
      "tag": "new",
      "description": "We are introducing new full-width site layout. <p><i class='p-icon--warning'></i> This is an experimental feature, currenly meant for internal use on our design system site and docs.</p>"
    }
  ],
  "3.10.0": [
    {
      "name": "Icons",
      "link": "/docs/patterns/icons",
      "tag": "new",
      "description": "We've added new desktop icon <code>.p-icon--desktop</code>."
    },
    {
      "name": "Typography" ,
      "link": "/docs/base/typography",
      "tag": "updated",
      "description": "We've introduced the new variable Ubuntu font and updated the default font weights."
    }
  ]
}
```

This data could maybe even be used to, by looking at the items from the most recent version number, automatically apply labels to section that have changed.

![image](https://user-images.githubusercontent.com/11927929/220596584-99112fe8-f80c-4953-a2c0-1b7bb9c3fd63.png)

This way the only thing we'd need to edit would be this JSON/YAML file and the site would respond accordingly.

**Comment by bartaz** [comment]
Even better: YAML instead of JSON.
