### ISSUE TITLE
p-heading-icon--long use case

### ISSUE THREAD

**Issue by petesfrench** [canonical/vanilla-framework#4678]
Apologies if this is the wrong type of issue, I wasn't sure if this counted as an amendment or new pattern.

## Pattern to amend

`p-heading-icon` to include `p-heading-icon--long`

## Visual

![image](https://user-images.githubusercontent.com/58276363/222375273-b9ca91a0-7530-4f04-909f-38a2ef66b2d5.png)

My hacky solution:
```
.p-heading-icon--long {
  .p-heading-icon__img {
    width: auto;
    height: 2rem;
  }

  .p-heading-icon__title {
    @extend .p-heading--5;
    margin-top: 1.5rem;
  }

}
```

## Context

I've seen this pattern appear in multiple places and usually implemented in different ways. Having a standard pattern for it would be useful.

I looked briefly for a similar pattern but did not find one.

**Comment by bartaz** [comment]
Does it need a component at all? It seems to be a logo image on top of heading / text. 

The "heading icon" component is about placing an icon next to the heading, this versions seems to put logo above the heading (or other text) which should be easily possible without any component.

**Comment by petesfrench** [comment]
I would have done it without a component, but I saw there was an [is-stacked](https://vanillaframework.io/docs/patterns/heading-icon#stacked) variation for `p-heading-icon' which led me believe we wanted to encapsulate this style

**Comment by bartaz** [comment]
Fair point, it looks like your proposal could be an extension of stacked version.

I'm now questioning if we need the stacked version, but it doesn't invalidate that proposal.

I think it's likely we may wait with any changes till we know more about future branding updates that will come from agency work that may affect different styles we propose, but we will take that type of component into consideration then.

**Comment by lyubomir-popov** [comment]
Baking in heading styles like this is always problematic. The choice of heading depends on its place within a page's hierarchy, while the component is supposed to be a reusable piece of content you can drop anywhere within that hierarchy. We would either need to test and make sure this works with all headings, or just use normal markup to achieve the above. I woul opt for the latter.

**Comment by danielmutis** [comment]
@bartaz to respond to this.

**Comment by bartaz** [comment]
Based on previous comments and discussion in working group it seems we don't feel the need to include it as a specific pattern.

Hopefully this kind of grouping of logo and text can be achieved without the use of any specific component. The "heading icon" component was mostly of the case of having circular icon next to a heading text.

Having a logo above a heading hopefully doesn't require any specific component class names.

If you have any issues with achieving the desired structure with styles in Vanilla please let us know.
