### ISSUE TITLE
New layout doesn't work well when page is too short

### ISSUE THREAD

**Issue by bartaz** [canonical/vanilla-framework#4689]
**Describe the bug**

When page doesn't have enough content to fill the screen there is a weird scrolling bug on new layout. A small white space appears below side navigation not covered by side navigation backround.

**To Reproduce**

https://vanillaframework.io/docs/settings/assets-settings

**Screenshots**

![layout-bug](https://user-images.githubusercontent.com/83575/223434705-40474256-3d75-48de-9fe5-3fa315fe96cf.gif)

**Comment by lemacarl** [comment]
@bartaz Looks like removing/disabling the height property fixes this problem. What are your thoughts on this as a fix?

![ezgif-3-4428f08e3c](https://github.com/canonical/vanilla-framework/assets/14212201/e52e4d06-bf38-41aa-abcc-f28f90a013f2)

**Comment by bartaz** [comment]
@lemacarl Thanks for looking into that! I would need to verify why the height is set there. It may have been needed for scroll of the navigation, or when it's sticky… So I'm not sure if simply removing it wont have other consequences.

**Comment by bartaz** [comment]
Tracked in https://warthogs.atlassian.net/browse/WD-6053

**Comment by bartaz** [comment]
We are reworking the layout and using new documentation layout instead #4886
