### ISSUE TITLE
Ticked list does not indent when wrapped anymore 

### ISSUE THREAD

**Issue by anthonydillon** [canonical/vanilla-framework#4696]
**Describe the bug**

Ticked list does not indent when wrapped anymore.

**To Reproduce**

1. Go to https://vanillaframework.io/docs/patterns/lists#ticked-with-horizontal-divider
2. Edit the content of the list item to wrap

**Expected behavior**

The wrapped line should be indented as the first line.

**Screenshots**

![image](https://user-images.githubusercontent.com/1413534/224290921-87af00df-239f-421d-8951-1783efa69649.png)

| Before (v3.11.1) | After (v3.12.1) |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1413534/224291057-868c9c29-5e6f-4207-8c45-af10123e9972.png) | ![image](https://user-images.githubusercontent.com/1413534/224291146-ec74f116-f3d1-46fa-b000-84bdf9c08fbb.png) |

**Comment by lyubomir-popov** [comment]
@ClementChaumel didn't we fix this? I remember we discussed it when we talked about the inline-block / overflow:auto technique

**Comment by bartaz** [comment]
> @ClementChaumel didn't we fix this? I remember we discussed it when we talked about the inline-block / overflow:auto technique

@lyubomir-popov I also think we looked at examples with wrapped lines, but must have been one of earlier versions… The`overflow: auto` won't work here I think, because there is no element on which this could be applied. Text is directly in `<li>` element, so is the bullet/tick.
