### ISSUE TITLE
Ampersand lacks a small-caps glyph

### ISSUE THREAD

**Issue by fitojb** [canonical/vanilla-framework#4698]
Similar to #4697, the ampersand character doesn't adapt to the `all-small-caps` value of the `font-variant-caps` CSS property, due to the lack of a glyph in the font. Example from maas.io: 
![image](https://user-images.githubusercontent.com/554953/224503793-0f85c18b-29a1-4c64-b405-537995c45d9f.png)

**Comment by bartaz** [comment]
Fixed in Vanilla 4.0 via https://github.com/canonical/vanilla-framework/pull/4812
