### ISSUE TITLE
Upstream Figma components from MAAS to the Vanilla Figma library

### ISSUE THREAD

**Issue by dgtlntv** [canonical/vanilla-framework#4705]
I build [Figma components for MAAS ](https://www.figma.com/file/D02aKXICVGBJpT3WpvzHAg/MAAS-Components?node-id=1%3A2&t=DdzSLRILlCcmfoiW-1). Maybe some of them can be upstreamed to the Vanilla Figma library.
This is not a proposal to introduce new components into Vanilla, but only to update or add Figma components to the Vanilla-Figma library that are not yet there.

**Comment by lyubomir-popov** [comment]
Can you please break it down into individual issues for each proposed figma component, and we can review these one by one.
