### ISSUE TITLE
p-text--small-caps lacks sufficient margin bottom

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4713]
It looks like it has had u-no-margin--bottom applied to it. It should have the same margin-bottom as the regular paragraph, as it is the same font-size:

![image](https://user-images.githubusercontent.com/2741678/227145295-4711eb93-7b1d-4b80-a9c2-84a3f9acf9bf.png)

**Comment by bartaz** [comment]
Fixed in #4807
