### ISSUE TITLE
Validation example with radio/checkboxes

### ISSUE THREAD

**Issue by minkyngkm** [canonical/vanilla-framework#4716]
As mentioned on MM, validation examples for checkboxes and radio buttons don't exist in the documentation https://vanillaframework.io/docs/base/forms#validation 

It would be great if validation is available for checkboxes/radio buttons :)

**Comment by bartaz** [comment]
Scope of the issue:

- add an example of form validation with checkboxes (either as a new example or added to existing validation example)
