### ISSUE TITLE
Please add u-no-margin--bottom on all hrs in the brochure guide

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4728]
They should be like so:

<hr class="is-fixed-width u-no-margin--bottom">

The margin is there to prevent block elements like images, videos, etc from sticking to the hr, which is unsightly. when followed by text, hrs need no margin-bottom. 

Wondering if there's a way to just get rid of it and apply a .5rem margin-top on all elements of type video/img, which we then selectively remove where needed (e.g. in a site's logo). Might make things simpler and easier.

**Comment by bartaz** [comment]
We are creating a `p-rule` component that is meant to replace the use of hr in new style of dividers, and it will have no margin bottom.

I don't think we should add margin top on all media elements. This for one will break our rule of not having top margins and may cause unexpected shifts of content in various places that already use images or video.

But of course, we can fix our brochure style guide to remove the margins and eventually use the new rule component there instead.
