### ISSUE TITLE
Navigation chevron is too low on mobile view

### ISSUE THREAD

**Issue by petesfrench** [canonical/vanilla-framework#4758]
## Pattern to amend

p-navigation

## Visual

![image](https://user-images.githubusercontent.com/58276363/236145234-feb1528e-0660-43f6-9433-0f2c5c36bdfc.png)

## Context

The chevron is too low on mobile view

**Comment by bartaz** [comment]
Good catch, indeed, it seems that top should be `1rem` instead of `1.25rem` (on mobile). Currently it's positioned in same way as on desktop view, which is different.
