### ISSUE TITLE
25/75 layout needs a tablet version

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4762]
Before:
![image](https://user-images.githubusercontent.com/2741678/237039059-bbbb95b2-1f64-4632-93d3-430017085eaf.png)

After:
![image](https://user-images.githubusercontent.com/2741678/237039010-5b546566-667a-4b17-b89a-2b2a0ba46507.png)

**Comment by bartaz** [comment]
or should we divide 6 columns as 2 + 4 columns? But this will not follow the 25 split anymore…

**Comment by lyubomir-popov** [comment]
> or should we divide 6 columns as 2 + 4 columns? But this will not follow the 25 split anymore…

yes that's what we discussed in the londonf office sprint. naming things is hard, the name comes from the desktop arrangement, but we shouldn't allow that to result in sub-optimal responsive layouts. on the 6 col medium grid the 2+4 column split is  the only viable alternative
