### ISSUE TITLE
Tabs have white background

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4770]
We need a way to make this work with the paper theme - either a separate version of the tabs, or removing the background. 

![image](https://github.com/canonical/vanilla-framework/assets/2741678/041a746b-ec90-4582-98b1-974879b22f20)

**Comment by bartaz** [comment]
This was moved to JIRA, let's track it in one place. https://warthogs.atlassian.net/browse/WD-3885

**Comment by bartaz** [comment]
Fixed
