### ISSUE TITLE
Update nav column alignment so that the loog/bubble part takes up 3 columns on desktop

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4782]
Like so
![image](https://github.com/canonical/vanilla-framework/assets/2741678/e657db06-4c19-49fe-bdcd-9ac29c4d6b05)

**Comment by lyubomir-popov** [comment]
I would be fine if we simply adjust the current hardcoded logo area width to match the grid

**Comment by bartaz** [comment]
Already fixed.
