### ISSUE TITLE
Please update to latest variable font (0.869) version

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4785]
I've merged that branch into main, so you can pick it up from here https://github.com/canonical/Ubuntu-fonts/tree/main/fonts/variable

We will  need an example showing how to do old style text figures:
![image](https://github.com/canonical/vanilla-framework/assets/2741678/6274336d-25da-48c4-8d7c-1be122bb5809)

Also, can  we verify if this weight discrepancy is happening in css? It does so in figma - these are regular and italic at 400:

![image](https://github.com/canonical/vanilla-framework/assets/2741678/a3accb60-7418-472d-b268-a2815af26aa3)

**Comment by bartaz** [comment]
Done in Vanilla 4.0
