### ISSUE TITLE
Logo spacing wrong

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4789]
Can we please increase the spacing between text and tag by 3px? This amount was discussed with @marcushas in the visual design meeting.

![image](https://github.com/canonical/vanilla-framework/assets/2741678/65337d65-4081-4339-a719-8b1d0bb47901)

**Comment by lyubomir-popov** [comment]
(assuming the current snapcraft page is a reflection of what is currently in vanilla)

**Comment by bartaz** [comment]
3px won't scale up with the font size. Should we reflect that in rems?

**Comment by lyubomir-popov** [comment]
yes can be in rems, thanks.
