### ISSUE TITLE
Change ticks in ticked list

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4790]
Ticks should be the grey ones, not green:
This has been flagged by @marcushas during the rebranding audit.

before:
![image](https://github.com/canonical/vanilla-framework/assets/2741678/cfc94b4c-2cda-4acb-a88b-115c62745912)

after: 
![image](https://github.com/canonical/vanilla-framework/assets/2741678/6fb62ec1-755f-4ea7-8448-f91e73661a4b)

**Comment by bartaz** [comment]
Fixed in https://github.com/canonical/vanilla-framework/pull/4792
