### ISSUE TITLE
Chips: small caps instead of uppercase, same fontsize for labels and values, 400 weight instead of 550

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4794]
Now that we have small cps, can we please make use of them in the chip labels? All text in chips can now be same size, regular weight.
We also don't need them to be bold, it looks strange - especially on linux:
![image](https://github.com/canonical/vanilla-framework/assets/2741678/50d885fe-89bb-4095-bd00-ec873600bd5e)

**Comment by lyubomir-popov** [comment]
Wasnb't this done @bartaz ?

**Comment by bartaz** [comment]
It was done in another issue, I guess this one can be closed.

But you can verify how they look now if there is anything else to address: 
https://vanillaframework.io/docs/patterns/chip
