### ISSUE TITLE
Tabs: Add image (and potentially heading) variants

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4800]
On the new p ro page, we are experimenting with testimonials inside tabs - to achieve that, we'll need to do something like this:
![image](https://github.com/canonical/vanilla-framework/assets/2741678/ee391ead-4c45-450e-9052-25bd5c4f2307)

I quickly tested it in the browser, seems to work ok if images are consistently sized and with transparent backgrounds - but we need to ensure accessibility is taken care of.

**Comment by danielmutis** [comment]
Not needed anymore.
