### ISSUE TITLE
Paper version of buttons

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4802]
White is baked into the buttons. Can we please have an `on-paper` version:

![image](https://github.com/canonical/vanilla-framework/assets/2741678/4a34a823-4a42-4811-a8e7-24d2ecd67fd6)

**Comment by lyubomir-popov** [comment]
(The dark version is currently discussed in a separate working group issue. We'd like to test how it performs on the /pro page)

**Comment by bartaz** [comment]
What are the hover and active states? These are also based on white background, should they stay the same as on white?

**Comment by lyubomir-popov** [comment]
I'll work on that this week, as part of the wider states update.

**Comment by bartaz** [comment]
@lyubomir-popov what is the status of this?

**Comment by danielmutis** [comment]
@bartaz to move it to the corresponding epics.

**Comment by bartaz** [comment]
To be done as part of theming update on buttons, tracked in JIRA: https://warthogs.atlassian.net/browse/WD-7595
