### ISSUE TITLE
Set small caps styles to use old style figures by default

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4806]
The latest version of the variable font includes small caps and matching text figures. However, the css isn't configured to make use of those.

I think we should consider making them the default everywhere, but as a first step - ca nwe please make them the default in small caps headings:

https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric
`font-variant-numeric: oldstyle-nums;`

Comparison:

![image](https://github.com/canonical/vanilla-framework/assets/2741678/86062770-daf1-4503-a5aa-f14eabd61577)

**Comment by bartaz** [comment]
I don't think we updated to the latest font yet. So this can be done as part of it.

**Comment by bartaz** [comment]
Tracked in [WD-4816](https://warthogs.atlassian.net/browse/WD-4816)
