### ISSUE TITLE
Image shadowed doesn't do anything

### ISSUE THREAD

**Issue by anthonydillon** [canonical/vanilla-framework#4815]
**Describe the bug**

[Image shadowed is documented](https://vanillaframework.io/docs/patterns/images#image-with-drop-shadow) by seems to have been removed. This documentation should be removed from the docs if that is the case.

**Comment by bartaz** [comment]
It does have (a very faint) drop shadow:

<img width="1236" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/4ea63ef2-ea36-4077-acdc-38e047092e94">

We will be cleaning up legacy components towards 5.0

**Comment by anthonydillon** [comment]
Oh it's very faint but I see it zoomed in... 👴
