### ISSUE TITLE
How to use JS components ?

### ISSUE THREAD

**Issue by martinzerty** [canonical/vanilla-framework#4822]
**Describe the bug**

I would like to use vanilla framework for a flask app with jinja. So I import the css with `link rel="stylesheet" href="https://assets.ubuntu.com/v1/vanilla-framework-version-3.15.1.min.css" />` but I would also like to have JS features.
In the documentation, it is never mentioned where to get the scripts to make certain components work. Only says things like "*will require JavaScript to handle interaction*".

Can someone help me to use JS with vanilla CSS ?

**Comment by bartaz** [comment]
Hi @martinzerty, thanks for reaching out.

Yes, Vanilla is mostly a CSS framework so the npm package only contains SCSS files, and we publish only CSS.

For any JS functionality, we provide an example in the documentation, and you can check the JS code needed by switching from HTML to JS in the example dropdown:

<img width="1239" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/e323034a-bc2c-44e9-8500-04a46b1ddb03">

This code can be copied to your application and website, but please note that this JS is mostly created to support the examples and may need some modifications if your components are a bit different.

**Comment by martinzerty** [comment]
Ok ! I thought this button for for other framework like react.
Thanks a lot !!
