### ISSUE TITLE
Retain width for matrix rows with less than three items 

### ISSUE THREAD

**Issue by mtruj013** [canonical/vanilla-framework#4828]
## Pattern to amend

https://vanillaframework.io/docs/patterns/matrix

## Visual

![Screenshot from 2023-07-12 10-08-22](https://github.com/canonical/vanilla-framework/assets/17607612/4f7e88ca-4106-4e72-96d7-aaf73fee00ec)

## Context

This came up because we were asked to add a new matrix item on docs.ubuntu.com, however the current pattern does not take into account that there may be rows with less than three items. It works if you add a bit of custom styling but would be great if the pattern were updated to handle this. 

Relevant PR [here](https://github.com/canonical/docs.ubuntu.com/pull/358).

**Comment by bartaz** [comment]
Matrix is a pattern that is likely going to be discontinued with new rebranding.

@lyubomir-popov do you have any suggestion what this can be replaced with (without redesigning the whole page)? Maybe cards instead of matrix for now?

**Comment by lyubomir-popov** [comment]
I would propose a simple list in this format - that we can later componentise:
[ section h2 3 columns] [logo / icon + title 3 columns ] [ description 6 columns ]

**Comment by danielmutis** [comment]
We won't address the matrix component at this time, because it's being phased out. Being a multiple of 3 should be a requirement to use this component, otherwise the list component should be used, as per the proposal above.

**Comment by danielmutis** [comment]
@bartaz to remember this for adding a deprecated message.

**Comment by bartaz** [comment]
Follow up issue reported to JIRA: https://warthogs.atlassian.net/browse/WD-7945
