### ISSUE TITLE
Chip border too heavy (1.5 instead of 1px), font-weight too heavy too

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4834]
Proposal to change chips to be more subtle:

Before 
<img width="395" alt="image" src="https://github.com/canonical/vanilla-framework/assets/2741678/d780051c-d254-4da5-bf1e-8831e35a1204">

After
<img width="284" alt="image" src="https://github.com/canonical/vanilla-framework/assets/2741678/75f318bc-b132-46a0-b604-e8fd84cae292">

**Comment by lyubomir-popov** [comment]
Comment from Brand: borders only feel nicer: 
<img width="439" alt="image" src="https://github.com/canonical/vanilla-framework/assets/2741678/0a3e0405-eedf-44c7-857d-4d4bff1d1cf7">

**Comment by bartaz** [comment]
What exactly is the proposal here?
I get that we want the border thinner. But how about the font? Currently chips use 550 weight for both lead part (that uses fake small caps) and value part.

What do we want to change it to, for lead and value?

<img width="629" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/94be10fb-3db8-401a-ae10-fc752b0fe1c7">

And what about the background? Do we want to make it transparent? White? What about the coloured versions?

**Comment by bartaz** [comment]
I guess this is also duplicated (or related to): #4794

**Comment by lyubomir-popov** [comment]
weight 400 (the default weight for body text)

**Comment by bartaz** [comment]
JIRA: https://warthogs.atlassian.net/browse/WD-5198
