### ISSUE TITLE
Sorted table moves down by 1px

### ISSUE THREAD

**Issue by huwshimi** [canonical/vanilla-framework#4837]
**Describe the bug**

In Chrome when a table is sorted the content moves down by 1px and then when sorting is removed it moves back up.

**To Reproduce**

1. Go to https://vanillaframework.io/docs/base/tables#sortable.
2. Click on a header to sort the table.
3. See that the content moves down by 1px.

**Expected behavior**

The table content shouldn't move.

**Screenshots**

![Screen Recording 2023-07-18 at 9 38 17 am](https://github.com/canonical/vanilla-framework/assets/361637/5253db70-f619-46c1-a249-9765ec5eca76)

**Desktop (please complete the following information):**

- Browser: Chrome (seems fine in Firefox).

**Comment by aaryanporwal** [comment]
I can't seem to reproduce this, MacOS Chromium version 119.0.6045.159 (Official Build) (arm64) 
![Screen Recording 2023-11-23 at 1 51 57 PM](https://github.com/canonical/vanilla-framework/assets/54525904/f9043f73-5880-48fc-9e6c-747ff2d6c3e4)

**Comment by bartaz** [comment]
@huwshimi Are you still able to reproduce it?

**Comment by bartaz** [comment]
Can't reproduce. Please reopen if needed.
