### ISSUE TITLE
Updates to logo section with misaligned images

### ISSUE THREAD

**Issue by bartaz** [canonical/vanilla-framework#4875]
Based on work on ubuntu.com (https://github.com/canonical/ubuntu.com/pull/13131) we need to add some small styling amendments to logo section with misaligned images variant.

There should be a larger margin under the `__item` element (to better space out the logos), and images should have some max-height set, to prevent them from becoming too large (while keeping the aspect ratio).

**Comment by petesfrench** [comment]
I believe this can be closed as it exists in vanilla now?
