### ISSUE TITLE
Compiled CSS and JS

### ISSUE THREAD

**Issue by Dameen-Rainer** [canonical/vanilla-framework#4884]
Is there a plan to add ready-to-use compiled  CSS and JS filles to be directly include in local development projects as a third option? 

I think not everyone prefer to use yarn or npm to have those things set up.

**Comment by bartaz** [comment]
You can hotlink directly to Vanilla CSS from our servers (as per https://vanillaframework.io/docs#hotlink):

`<link rel="stylesheet" href="https://assets.ubuntu.com/v1/vanilla-framework-version-4.3.0.min.css" />`

Currently we don't export JS in any way unfortunately.

**Comment by Dameen-Rainer** [comment]
I use hotlink in production but it development I just copy the minified CSS to work with it locally it'll be easier that way.

Hope to see those available in future.

**Comment by bartaz** [comment]
Not sure why you can't use hotlinked CSS in development if you use it in production?

How would you want it to work? If you don't want to use yarn/npm to install/build the package, where do you want to get CSS from for local development?

**Comment by Dameen-Rainer** [comment]
I just copy the hotlink url to a browser as a Web address then the browser will show the minified CSS in plain text & then I copy it to a css file named after the version that I'm using.

You know direct hotlink requires Internet connection, so using it during development will be to costly here in Senegal.

**Comment by bartaz** [comment]
OK, thanks for the context, I didn't realise you meant offline use.

We can provide an option to download the same prebuilt CSS, so it would be a bit easier than coping the contents of the CSS opened in the browser, but the end result will be exactly the same.
