### ISSUE TITLE
Encoding issues of unicode content

### ISSUE THREAD

**Issue by Dameen-Rainer** [canonical/vanilla-framework#4889]
![Screenshot (70)](https://github.com/canonical/vanilla-framework/assets/85369780/fd24f60e-11b4-4ae2-b5e4-0bef8f9f6444)

My browsers seem to have problem rendering correct ::before and ::after contents.. They show weird symbols instead. This pic is when using quote classes.

 I'm using the minified precompiled css.

**Comment by bartaz** [comment]
Seems like character encoding may have got broken. 
Does it work when linking to online hosted version? https://assets.ubuntu.com/v1/vanilla-framework-version-4.3.0.min.css
Are you saving your file as UTF-8?

**Comment by Dameen-Rainer** [comment]
Yeah it works with online hosted version but I have no clue why it doesn't work with offline version.. And yeah I have <meta charset="UTF-8"> in my html file.

**Comment by bartaz** [comment]
We recently seen a similar issue in another place that was using Vanilla copy/pasted into `<style>` tag. 

How are you using your local version of Vanilla? Did you download it, or copy pasted @Dameen-Rainer ?
