### ISSUE TITLE
Main suru hidden on small screens

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4894]
## Pattern to amend

[Add pattern name(s) here](https://vanillaframework.io/docs/examples/patterns/suru/default)

## Visual

this suru disappears on small screens, but shouldn't. It is quite short in terms of height.
## Context

In what context does your amendment solve a problem?

**Comment by bartaz** [comment]
@lyubomir-popov So we don't want any special responsive treatment for it? It would simply scale down to any screen width?
