### ISSUE TITLE
Improve alignment of top navigation items with grid

### ISSUE THREAD

**Issue by bartaz** [canonical/vanilla-framework#4898]
## Context

Padding in top navigation items is different from padding on the grid. We want text of first item of top navigation to align with the content on the page below it. Hoverbox of the item should stick outside of the grid (text is aligned, but navigation items actually expands to the left).

Currently, because padding on item and grid are different they would misalign like this (if we align navigation with outside margin of the grid:

<img width="658" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/03edb753-24f8-4b1f-a1c3-ea25d0b9ef80">

Or like this (if we align both using same grid padding):

<img width="673" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/3fc2e968-9191-405b-b74c-dfe674e3b98f">

## Visual

On canonical.com it's hacked with some undocumented usage of grid in top navigation and negative margin:
<img width="1476" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/bc78caa5-cd0c-4d06-b2e6-68709e045b27">

We want to achieve this in docs layout as well (currently local styles):

<img width="1818" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/e586e372-1af8-45bc-84d1-1d1e2459b631">

We need to update the top navigation to improve the alignment with the grid below it, while making sure it still works on small screens and doesn't affect older websites that may still use old layout.

**Comment by lyubomir-popov** [comment]
Maybe we can modify the hover/active state to not use padding-left:
![image](https://github.com/canonical/vanilla-framework/assets/2741678/f81964e1-0c2b-4531-9e2c-b79e6606bd3e)
(Just a thought, we  need to discuss this in the Design team)

**Comment by bartaz** [comment]
Another (relatively simple to implement) solution could be to increase hover area padding to 1.5rem (making it the same as grid margin) so that it aligns naturaly:

<img width="1739" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/1e81d3d2-6a3d-4dda-8b3a-f34c61a8cdc7">

Although it does create 3rem space between unselected navigation items making it probably wider than needed (and may make some sites not fit their navigation - although we did increase the grid width in 4.0 so we have more space there).

**Comment by lyubomir-popov** [comment]
THat works for me. We've increased the fixed width fro m72 to 80 rem, which should compensate. Happy to go with that but we need to test maas and other sites with large numbers of menu items

**Comment by bartaz** [comment]
In JIRA as: [WD-8284](https://warthogs.atlassian.net/browse/WD-8284)

**Comment by bartaz** [comment]
Done
