### ISSUE TITLE
.u-fixed-width's padding-left and right not cleared when inside .row-25-75

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4925]
This looks like a vanilla bug @bartaz 
![image](https://github.com/canonical/vanilla-framework/assets/2741678/96f185b2-0298-4466-807e-15656edf2c05)

**Comment by chillkang** [comment]
I don't think I can reproduce this issue. I am on macOS version 120.0.6099.234 (Official Build) (x86_64) 
<img width="1129" alt="Screenshot 2024-02-05 at 9 25 35 PM" src="https://github.com/canonical/vanilla-framework/assets/90341644/32311a63-da89-4842-990a-5a935e49fdae">
