### ISSUE TITLE
hr.is-extra-muted

### ISSUE THREAD

**Issue by petesfrench** [canonical/vanilla-framework#4955]
A component in Vanilla needs to be flexible enough that it can be used across a wide range of scenarios and shouldn't be constrained to a specific number of applications.

## Visual

Look at the `<hr>` at the top of the list:
![image](https://github.com/canonical/vanilla-framework/assets/58276363/0010bf32-d3ac-437d-ad2f-65e164a4f0c1)

## Context

I've seen it being use sometimes above and/or below lists in multiple pages in the desktop bubble. My use case was on this page: https://ubuntu-com-13491.demos.haus/desktop/developers base on this design: https://www.figma.com/file/wLOtPeQhAiExhQCwKYhi3H/24.04-U.com---desktop-(rebranding)?type=design&node-id=1-2&mode=design&t=Fb5N2muecteluj8U-0

```
hr.is-extra-muted {
  background-color: rgba(0,0,0,.1);
  opacity: 0.5;
}
```

**Comment by bartaz** [comment]
The use of `<hr>` should be limited. We have a [rule component](https://vanillaframework.io/docs/patterns/rule) now that should provide all necessary variants, but indeed we don't have such heavy muted one there.

@lyubomir-popov Is our current set of rule variants enough? Do we need even more muted one?

**Comment by danielmutis** [comment]
WG: extra muted is not needed.

**Comment by bartaz** [comment]
@petesfrench Just for a bit more context - the current `p-rule--muted` is the preferred option (https://vanillaframework.io/docs/patterns/rule#muted). We should not need another muted variant.

If the design had a different amount of opacity on the borders, it was wrong.
