### ISSUE TITLE
"Manage your tracker settings" link in Vanilla documentation doesn't work

### ISSUE THREAD

**Issue by Johnylab** [canonical/vanilla-framework#4959]
**Describe the bug**

Clicking the link in the website's footer doesn't have any effect on clicking. No network events or console messages.

**To Reproduce**

1. Go to [Vanilla documentation](https://vanillaframework.io/)
3. Scroll down to the end of the page
4. Click "Manage your tracker settings"
5. See the hash added to the address bar
6. Nothing else happens

**Expected behavior**

I don't know what's the expected behavior, but I am looking for one of:

- some navigation happens
- the page scrolls to a specific point
- a modal opens
- any other UI element appears

**Screenshots**

<img width="1525" alt="image" src="https://github.com/canonical/vanilla-framework/assets/1944417/db9698f3-bc04-45a4-8ba5-e0b7ea06d871">

**Additional context**

I subscribed to the Vanilla Newsletter and confirmed my e-mail. I was searching for the newsletter history to review past editions, and that seemed to be the most direct route to what I was seeking.

**Comment by bartaz** [comment]
Thanks @Johnylab, indeed something got broken in our cookie policy dialog.

Have you been presented with cookie manager dialog when you first visited the website?

Like this one?
<img width="1232" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/e8b07689-05fa-4dd2-a23f-551907c43cd0">

Manage your tracked link should open the same dialog. It seems it only works on initial load, but not after cookies are already set.

**Comment by Johnylab** [comment]
Yes, I accepted all the cookies in the first render.
