### ISSUE TITLE
Add dark theme support for Notification component

### ISSUE THREAD

**Issue by britneywwc** [canonical/vanilla-framework#4961]
## Component/pattern to amend

Notification

## Visual

There is currently no dark theme support for the Notification component and only certain semantic colours exist for dark theme at the moment (negative and positive). 
Would be nice to also have support for other semantic colours such as caution and information, as used in Notification.

## Context

The dark Notification is used in the Support Portal, currently fixed with some custom stylings [PR here](https://github.com/canonical/support-portal/pull/159).

**Comment by bartaz** [comment]
We can try to do it as part of the dark theme migration this pulse.

**Comment by bartaz** [comment]
In JIRA as https://warthogs.atlassian.net/browse/WD-8572

**Comment by britneywwc** [comment]
Fixed here https://github.com/canonical/vanilla-framework/pull/4971
