### ISSUE TITLE
Notifications partially overlap elements with z-index = 1

### ISSUE THREAD

**Issue by vladimir-cucu** [canonical/vanilla-framework#4990]
**Describe the bug**

Notifications partially overlap elements that have `z-index = 1` (as can be seen in the attached screenshot). The colored vertical strip of the notification overlaps, while the rest of the notification goes underneath the element with `z-index = 1`.

**Expected behavior**

The notifications should either entirely overlap the elements that have `z-index = 1` or entirely go underneath them.

**Screenshots**

[Screencast from 02-13-2024 10:24:02 AM.webm](https://github.com/canonical/vanilla-framework/assets/108150922/61c4edd8-8dc7-4129-942f-e721932a049d)

**Desktop:**

- OS: Ubuntu 22.04.3 LTS
- Browser: Google Chrome
- Version: 121.0.6167.160 (Official Build) (64-bit)

**Additional context**
The top navigation bar in the attached screenshot has `z-index = 1`. Setting `z-index > 1` for the top navigation bar temporarily fixes this issue. On a side note, the colored vertical strip of the "negative" notification is set to have `z-index = 1` at line 235 in `scss/_paterns_notifications.scss`, where we call `@include vf-highlight-bar($color-negative, left, true)`.

**Comment by bartaz** [comment]
@vladimir-cucu Thanks. I will have a look if we can remove z-index from notifications (and/or highlight bars). 

But overall, to avoid such issues, I'd suggest not using z-index of 1 on anything that is supposed to be on top of other things. We don't have any solid guidelines around that, as this is always kind of a chicken-and-egg problem of finding things that are supposed to be on top of each other and those that don't.

We have this example which features various of overlaying elements in Vanilla: https://vanillaframework.io/docs/examples/templates/z-index

You can use that to have a look at their z-indexes. 
Overall modals, etc (on top of everything) use 100 or above.
Tooltips are at 11. Contextual menu at 9.
Top navigation (dropdowns) are at 5.
Flat content may have things at 1.

Based on that I'd suggest placing your top navigation somewhere between 5-10.

**Comment by vladimir-cucu** [comment]
@bartaz Thanks for the detailed explanation! We'll set the `z-index` to 5 as suggested.

**Comment by huwshimi** [comment]
> Based on that I'd suggest placing your top navigation somewhere between 5-10.

Just in case it's not clear, that top nav is from the application layout and the `z-index` is set to `1` here: https://github.com/canonical/vanilla-framework/blob/main/scss/_layouts_application-panels.scss#L24.

Should we update the sticky header `z-index` to `5` in Vanilla to fix it for everyone or is that likely to cause other issues?

**Comment by bartaz** [comment]
Ah, sorry. I was looking for that into application layout, but missed that it's only in sticky option.
Of course it makes sense to fix it directly there.
