### ISSUE TITLE
Stepped lists grid is broken in small screens

### ISSUE THREAD

**Issue by carkod** [canonical/vanilla-framework#5002]
**Describe the bug**

Grid extends incorrectly in small screens.

**To Reproduce**

1. Go to this codepen with the Vanilla https://codepen.io/carkod/pen/mdovJWr
2. Make the screen "mobile sized" ($breakpoint-small)
3. Use the inspector tool as below

![Screenshot from 2024-02-19 17-15-39](https://github.com/canonical/vanilla-framework/assets/14939793/ebcecebc-4cf9-48ba-bd49-f9303773476d)

So as you can see if you turn on the grid button on any `li` element, the grid overlaps at the end.

**Expected behavior**

Grid should take have less span. Take a look at this [quick fix ](https://github.com/canonical/ubuntu.com/pull/13580/files#diff-f5a5b0429dba7d86dd96396c39539ab3a091d90536bccb9db008a3dbc487f83dR1506)

**Comment by bartaz** [comment]
Stepped list detailed seems to always use 6 column span for `p-stepped-list__title` (it seems that `__content` is using 4 columns on mobile, as expected).
