### ISSUE TITLE
Broken Link to Alphabet of Accessibility Issues

### ISSUE THREAD

**Issue by tanyabouman** [canonical/vanilla-framework#5017]
**Describe the bug**

On the [Accessibility page](https://vanillaframework.io/accessibility) the link to Accessibility Alphabet no longer exists.

**Additional context**

There is a copy of the article on [LinkedIn](https://www.linkedin.com/pulse/alphabet-accessibility-issues-anne-gibson-parimala-hariprasad).  It's also archived on the [Internet Archive](http://web.archive.org/web/20230307004829/https://the-pastry-box-project.net/anne-gibson/2014-july-31).

**Comment by bartaz** [comment]
Oh, that's too bad. It was a great article.
Thanks for providing the alternative links for the resource, we will update the link.
