### ISSUE TITLE
Slider shows white background on paper theme with Firefox

### ISSUE THREAD

**Issue by carkod** [canonical/vanilla-framework#5025]
**Describe the bug**

Slider shows white background only with Firefox.

This seems a weird one, looks like a discrepancy in web standard. I couldn't fix it without breaking the other.

**To Reproduce**

1. Here is a codepen with paper background https://codepen.io/carkod/full/rNbePQp
2. Open it with Firefox, you'll see white background, however if you open it with Chrome it doesn't.

**Expected behavior**

Not sure what is the right thing to do here.
- Override Firefox or override Chrome?
- Target using CSS for a specific browser? 

In any case they both should probably look the same.

[Quick dirty fix](https://github.com/canonical/ubuntu.com/blob/0ca3d9f67055cb7a3a659acdb8ca073df60dfbe6/static/sass/styles.scss#L1512)

**Screenshots**

**Desktop (please complete the following information):**

- Browser: Firefox, I'm using 123.0.1 (64-bit), but I bet it happens to any version

**Comment by bartaz** [comment]
Thanks. 

As far as I remember we already have 2 separate implementations for Chrome and Firefox, because only one of those (Firefox?) follows the standard fully and the other requires JS to style the progress on range slider.

We will have a look if it's still the case or maybe Chrome did fix it in the meantime allowing us to have one consitent implementation, and fix the issue with the background on paper theme.

**Comment by schalkneethling** [comment]
@bartaz - If you add `background: transparent;` to the range input it resolves the white background problem in Firefox. 

Does the framework add `appearance: none;` and the background gradient in Chrome to mimic the color of the range input in Firefox? I notice if you remove the `appearance` rule you lose the color match, but everything else works as expected.

There is also some additional styling applied in Chromium using `::-webkit-slider-runnable-track` but this is not on any standards track at the moment so, might it be a good idea to accept the slight difference in rendering across browsers, save some bytes, and wait for the work being done to make form element stylable?

Let me know what you think. Thanks!
