### ISSUE TITLE
Grid: provide 3 levels of nesting

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#5033]
## Component/pattern to amend

The grid currently works to a dpeth of 2 levels of nesting. 

Here's a design that needs 3: 

medium screens: 
![image](https://github.com/canonical/vanilla-framework/assets/2741678/672982f4-d910-40b2-9207-ddb8102e5cb6)

large screens: 
![image](https://github.com/canonical/vanilla-framework/assets/2741678/4beccd9a-54d7-40ff-bb4f-9a6a33baf6de)

And here's what happens when you try to build it:
![image](https://github.com/canonical/vanilla-framework/assets/2741678/29bda9f8-2b7a-4c30-8c40-ef7ad0ea8c29)

Can we please add the 3rd level, including for .row--* components

**Comment by lyubomir-popov** [comment]
Seems to not work even at just 2 levels of nesting: 
![image](https://github.com/canonical/vanilla-framework/assets/2741678/a3e34d0f-83b6-405d-b851-6d3d258743f6)

**Comment by lyubomir-popov** [comment]
Something very strange, we do have at least 2 nested levels defined in the css - see top right, but it doesn't work:
![image](https://github.com/canonical/vanilla-framework/assets/2741678/48b4bb00-961c-4de9-ba35-4f80b75f1ca4)

**Comment by bartaz** [comment]
@lyubomir-popov can you paste links to the pages where it actually happens, there maybe something else going on

Nesting does work on Vanilla grid: https://vanillaframework.io/docs/examples/patterns/grid/nested

**Comment by lyubomir-popov** [comment]
ended up doing something else, so no actual pr with this.

**Comment by lyubomir-popov** [comment]
@bartaz but just pasting the markup above into the vanilla nesting example (no css other than what is in vanilla), it still doesn't work:

![image](https://github.com/canonical/vanilla-framework/assets/2741678/810ce2f4-5974-49ad-8821-efd77d2b3aa5)

**Comment by lyubomir-popov** [comment]
think I found it - this works:
![image](https://github.com/canonical/vanilla-framework/assets/2741678/2a3661ad-4701-469d-aa61-6cd32df3ff6a)

this doesn't:
![image](https://github.com/canonical/vanilla-framework/assets/2741678/1d1ea0c5-ab34-407a-9e95-a37bed2bc536)

**Comment by bartaz** [comment]
> this doesn't: ![image](https://private-user-images.githubusercontent.com/2741678/316036083-1d1ea0c5-ab34-407a-9e95-a37bed2bc536.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTU5MDMsIm5iZiI6MTcxMTExNTYwMywicGF0aCI6Ii8yNzQxNjc4LzMxNjAzNjA4My0xZDFlYTBjNS1hYjM0LTQwN2EtOWU5NS1hMzdiZWQyYmM1MzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMTM1MzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzhmZDM2OTk1Y2RiMzRkM2Y1YTQ5ZDEyOWRlOTcyNzkxYTc4YzM5MjQ5NjRiMDQyNzIxNmM0ZDYzZTRlZWUzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jmDNNlzQc_dK1SoXvubtp8_jXWcD9nHCGDggaoPLXmI)

@lyubomir-popov this doesn't work because there is no col defined for desktop, so it likely assumes 12 column. It needs to define how many columns on desktop it uses.

**Comment by bartaz** [comment]
Grid nesting works as expected, to any level with standard low level grid class names (`row`, etc).

With shorthand `row--25-75` nesting works on first level (`row--25-75` > `col` > `row`), but fails on deeper levels. Issue seems to be caused by CSS specificity and conflict between styles applied by standard `.col-X > .row` vs styles applied by `row--25-75`.

So we can have a look at fixing this on deeper levels. But it may require making some strict assumptions on markup (such as nested `row` is always direct child of it's parent `col-`), because otherwise nested rows will not know which of parent cols should define it's size.

**Comment by bartaz** [comment]
@lyubomir-popov BTW, by "3 levels of nesting" do you mean, having 3 grids:

`row--25-75` > nested `row` > another nested `row`

or actually 3 nested grids, 4 in total?

`row--25-75` > nested `row` > nested `row` > nested `row` (which seems like a lot)

**Comment by bartaz** [comment]
Triage: Looks like quite likely grid works as expected (at least in most cases). Adding more nesting functionality is quite high effort to address it now, with relatively low impact (we don't need it too often). Dropping for now, grid can be revisited in new architecture.
