### ISSUE TITLE
(Firefox) Holding shift while clicking a checkbox causes the click to not be registered

### ISSUE THREAD

**Issue by ndv99** [canonical/vanilla-framework#5044]
**Describe the bug**

In Firefox, if you hold down your shift key on a keyboard and click a checkbox, the click is not registered.

**To Reproduce**

1. Go to https://vanillaframework.io/docs/base/forms#checkbox
2. Shift + click on a checkbox
3. See checkbox _not_ being checked

**Expected behavior**

1. Go to https://vanillaframework.io/docs/base/forms#checkbox
2. Shift + click on a checkbox
3. See checkbox being checked

**Desktop (please complete the following information):**

- OS: Kubuntu 23.10
- Browser: Firefox (snap)
- Version 124.0

**Additional context**

This appears to be related to a ["bug" in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=559506) where shift+clicking checkbox labels doesn't check the checkbox. Vanilla checkboxes are also always wrapped in a label, hence the behaviour we see.

**Comment by bartaz** [comment]
Well, that doesn't look promising:

<img width="418" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/a3144be3-dc00-4795-87b7-ce8ddc8fd67f">

**Comment by ndv99** [comment]
> Well, that doesn't look promising:

My thoughts exactly :joy:

**Comment by bartaz** [comment]
Thanks for context @ndv99, I'm not sure if there is much we can do to remedy that.

BTW, what's the context of shift+click being used? You wanted to implement some kind of batch selection?

**Comment by ndv99** [comment]
> Thanks for context @ndv99, I'm not sure if there is much we can do to remedy that.
> 
> BTW, what's the context of shift+click being used? You wanted to implement some kind of batch selection?

You're absolutely right. We've implemented batch selection of machines in MAAS UI with shift+click. Works on Chrome, just not on FF :(

**Comment by petermakowski** [comment]
@bartaz @ndv99 I decided to give it a go and try and fix that Firefox bug. Here's a patch (no idea if or when it would get merged, but attaching it here for reference): https://bugzilla.mozilla.org/show_bug.cgi?id=559506#c24

> Well, that doesn't look promising:
> 
> <img alt="image" width="418" src="https://private-user-images.githubusercontent.com/83575/319232204-a3144be3-dc00-4795-87b7-ce8ddc8fd67f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTU4ODcsIm5iZiI6MTcxNjIxNTU4NywicGF0aCI6Ii84MzU3NS8zMTkyMzIyMDQtYTMxNDRiZTMtZGMwMC00Nzk1LTg3YjctY2U4ZGRjOGZkNjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE0MzMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YzUxNjQzMTYyNzcyMTNjNmNiNGZkZmZjZDQ1NDM5OTgyM2JiNmY1ZmVhZTgyOTlmMzYxNTUxYTY2OTIyNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tUZUMCyVV8f9pFYTsVSvXWvJq_wDkH-urm0og5-uqjQ">

**Comment by petermakowski** [comment]
Closing. My patch has been accepted by folks at mozilla and is ready to land.  

https://phabricator.services.mozilla.com/D211022#7354256

**Comment by bartaz** [comment]
Awesome news! Thanks for fixing it at the source @petermakowski !
