### ISSUE TITLE
p-equal-height-row: remove padding-bottom, make separators muted

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#5065]
Can we please:

1. remove the padding-bottom. Sometimes a section contains other ocntent underneath, so the end of section regular ssection spacing doesn't work here. best to let people wrap it in p-section or p-section--shallow as needed 

2. Can we please make the separators muted. I'm introducing a new convention of making section level `hr`s default colour, and any secondary `hr`s inside a given section - muted colour. This makes it easier to see which section things are part of. 

For example, in the below screenshot, the divider inside the equal height row should be muted, not default colour as it is here. Also notice the duplicated spacing at the bottom due to [1] ^ 
![image](https://github.com/canonical/vanilla-framework/assets/2741678/f8dd05e3-fe97-4290-a883-293687acfb58)

3. have a 1 char difference between 1st, 2nd, 3rd separator - 3chars slows you down

**Comment by lyubomir-popov** [comment]
also, a bug: we need the third separator hidden on medium:
![image](https://github.com/canonical/vanilla-framework/assets/2741678/a165dba2-90c9-486f-9215-c7512052907d)

**Comment by bartaz** [comment]
> also, a bug: we need the third separator hidden on medium

@lyubomir-popov we have a bug open for the separators: #5062

**Comment by bartaz** [comment]
In JIRA as: https://warthogs.atlassian.net/browse/WD-10920
