### ISSUE TITLE
The keyword 'searchfield-cancel-button' used on the 'appearance' property was deprecated and has now been removed. It will no longer have any effect.

### ISSUE THREAD

**Issue by dimaqq** [canonical/vanilla-framework#5088]
**Describe the bug**

Chrome complains about the deprecated feature:

`The keyword 'searchfield-cancel-button' used on the 'appearance' property was deprecated and has now been removed. It will no longer have any effect.`

**To Reproduce**

1. Go to https://juju.is/docs/juju/lxd#heading--create-a-controller
2. Look at console

**Additional context**

Looking through the code, I'm not entirely sure about the ultimate source, but git blame for matching scss suggests that it's a very old bit of code.

**Comment by bartaz** [comment]
Thanks. Yes, this seems to be used in search box component:

<img width="2056" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/fa517d9b-699c-427d-bd58-7f5f5926bd70">

https://github.com/canonical/vanilla-framework/blob/4109529d291740aa752b4e24967ef0d056d157ae/scss/_base_forms.scss#L167-L170

We need to verify if it can be safely removed (and what effect that would have on webkit based browsers). Or find an supported alternative value.
