### ISSUE TITLE
extend navigation separators in the application layout navigation

### ISSUE THREAD

**Issue by AnnSoMuller** [canonical/vanilla-framework#5102]
## Navigation in Application layout

extend separators to full width

## Visual
![Screenshot 2024-05-29 at 11 52 44](https://github.com/canonical/vanilla-framework/assets/32699582/c4daa7f9-ecf5-456f-8d3e-52d19c305391)
![Screenshot 2024-05-29 at 11 52 52](https://github.com/canonical/vanilla-framework/assets/32699582/79babd61-3985-45ec-b444-d78ae19b2ae5)

## Context

In the application layout, in [snapcraft.io](http://snapcraft.io/) 
As a user I want to see separators between the navigation sections so that I visually recognise which sub-navigation items belong to witch section. 
It will reenforce the Information architecture.
For instance “settings” could belong to a specific store or the profil. With separators we make it clearer where it belongs.
Separators should be “all width” to be present when the navigation is collapsed

**Comment by danielmutis** [comment]
I am going to close this issue as we are going to revive the discussions on side navigation to try to reach a consensus. In summary, the separators can be used in the expanded side nav to group items with each other, but in the collapsed state we won't show any navigation items, except for the bottom ones which are the ones that refer to user-related pages (notifications, settings, log out).
