### ISSUE TITLE
Change icon alignment to `middle` when next to paragraph text

### ISSUE THREAD

**Issue by jmuzina** [canonical/vanilla-framework#5103]
## Component/pattern to amend
Icon
Set icons to `vertical-align: middle` when they are next to paragraph text.

## Visual
![image](https://github.com/canonical/vanilla-framework/assets/46915153/03b8f266-0723-4f22-9c83-deee86238478)

## Context
See comment from @lyubomir-popov : https://github.com/canonical/vanilla-framework/pull/5093#issuecomment-2137035576
comment from @jmuzina : https://github.com/canonical/vanilla-framework/pull/5093#issuecomment-2137510915

There is already some code for changing appearance of icons when next to various heading levels. Probably we can add some styling for icons inside `<p>` elements here:
https://github.com/canonical/vanilla-framework/blob/b1d651365b0714586e6ea14349dea763819c256e/scss/_patterns_icons.scss#L88

**Comment by bartaz** [comment]
Triaged: fix in v4. We have already a PR in progress for this.
