### ISSUE TITLE
Intermittent color theme variation in Percy builds

### ISSUE THREAD

**Issue by jmuzina** [canonical/vanilla-framework#5114]
**Describe the bug**

Since we merged the example color theme improvements, I've noticed that Percy builds sometimes vary slightly in theming. I.E., [this build](https://percy.io/bb49709b/vanilla-framework/builds/34632676/changed/1894212498?browser=chrome&browser_ids=56&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280). It appears that Percy is not waiting for color theming to be loaded fully (perhaps because color theme loading is asynchronous). 

Maybe we need to [wait for timeout or some selector](https://www.browserstack.com/docs/percy/take-percy-snapshots/snapshots-via-cli#advanced-options) before taking the Percy snapshot to ensure that color theme initial state is fully loaded before snapshot is taken.

**To Reproduce**

1. Make a PR that causes a Percy build
2. You may see color theme diffs. You can confirm this by navigating to the example on Vanilla itself and verifying that the color theme is correct (Percy is taking the snapshot just before the color theme is set).

**Expected behavior**

Percy takes snapshots in the intended color theme for an example, every time.

**Comment by bartaz** [comment]
I'm not exactly sure how is this possible. Isn't the default theme set already in HTML? How is theme loaded asynchronously?

**Comment by jmuzina** [comment]
@bartaz I think I mistook that build result for a Percy issue but it is actually an issue with how I attempted #5112 . The [example with the color change](https://vanillaframework.io/docs/examples/base/paper/input-on-paper?theme=paper) noted is using a `.p-card`, which had its color changed. I don't think there's an issue with Percy here at all, disregard!
