### ISSUE TITLE
Unnecessary capitalisation in tables

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#5115]
**Describe the bug**
@acarege asked whether values in a table (like the statuses here) should be capitalised. I see no reason for them to be. Can we change to lowercase?

![image](https://github.com/canonical/vanilla-framework/assets/2741678/e174a156-8f54-4950-bb0d-f04f289f2bd8)

**Comment by jmuzina** [comment]
With respect to your screenshot, are you referring to the values in the "Result" column? Are you just looking for something like this?

<img width="927" alt="Screenshot 2024-06-10 at 12 14 43 PM" src="https://github.com/canonical/vanilla-framework/assets/46915153/633aad0f-b534-4dc5-9a79-4d20d7380cf9">

**Comment by bartaz** [comment]
Are we making this official rule? There is a lot of places where some kind of "status", or predefined values are uppercased in tables:

<img width="1271" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/93f8b377-8c1a-419a-8217-78f6fdc1d641">

<img width="663" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/6a100219-6538-4b2f-8bfc-2633f4e13d3a">

<img width="661" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/1fba08be-4a98-40be-9a30-ae5a42fa2f35">




I think this used to be quite common in data tables (and others as you see above), so removing this will be quite a bit change if we decide to make it a rule. And also

**Comment by bartaz** [comment]
As a general guideline, I guess this should be raised on Vanilla WG.

**Comment by danielmutis** [comment]
WG: The table shouldn't capitalise anything by default. We need content guidelines which say when to capitalise or not a column of the table @Sophie-32 

We keep this ticket open just to track the work of the guidelines.
