### ISSUE TITLE
Equal heights component: subgrid on medium has more columns than needed

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#5190]
![image](https://github.com/canonical/vanilla-framework/assets/2741678/9bf3f5a4-47d3-41c4-bd57-3075ec785cf2)
we shouldn'tr have 6 cols available in there, it should align with the parent grid, so 4 columns

**Comment by bartaz** [comment]
This is wrong usage of the component @lyubomir-popov.

It was never intended to be nested on medium screens. On medium screens it's supposed to be full width. We only support nesting it inside `row--25-75-on-large`: https://vanillaframework.io/docs/patterns/equal-height-row#three-column-row

We don't have a design for how this should behave inside the 4 cols nested on medium screen.

This is not a bug, it's a new feature not available in the component.

**Comment by lyubomir-popov** [comment]
ah you're right, closing.
