### ISSUE TITLE
Space character causes unexpected spacing in Search & Filter examples

### ISSUE THREAD

**Issue by jmuzina** [canonical/vanilla-framework#5227]
**Describe the bug**

There is extra spacing present between search & filter chips that is only present in the Vanilla examples, not in React Components.

**To Reproduce**

1. Go to any Search and filter example (e.g., [default](https://vanillaframework.io/docs/examples/patterns/search-and-filter/default))
2. Open the search & filter panel
3. Observe that there is extra space between the chips, that is not present in React Components. This can be seen in dev console as whitespace characters.

**Expected behavior**

No extra spacing between the chips.

**Screenshots**
Expected behavior (React Components default example)
![image](https://github.com/user-attachments/assets/c4666471-1e97-4171-b30e-da8b17a3f9b0)
Actual behavior (Vanilla default example)
![image](https://github.com/user-attachments/assets/8be29889-c68e-4094-bcc8-2733364d3f49)

**Additional context**

Originally reported by @dgtlntv in [MM thread](https://chat.canonical.com/canonical/pl/nqdms3cu6fnsxf77djced4s9oa)

Per @lyubomir-popov : 
> The way to avoid it is to either set font-size: 0; in the container, or eliminate space in the markup. As any white space like code tabulation gets rendered as a single space

**Comment by bartaz** [comment]
Triage: low effort fix (just remove whitespace between buttons in Vanilla examples). Little downside (they would be a bit harder to read, as HTML formatting would be affected).
