### ISSUE TITLE
duplicate padding declaration on cards

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#5228]
[this ](https://github.com/canonical/vanilla-framework/blob/7f25054399beecea8a96c3837f911401b7e1e260/scss/_base_placeholders.scss#L56) as it is already defined in the placeholder above:
![image](https://github.com/user-attachments/assets/4ef3c430-1a86-4dff-bbd6-33c7b23c90bb)

**Comment by rishidyno** [comment]
Hi @anthonydillon  Could you please assign me this issue.

**Comment by jmuzina** [comment]
> Hi @anthonydillon Could you please assign me this issue.

Hi Rishi, thanks for your interest in contributing! I've assigned you the issue, best of luck and let us know if you have any troubles or concerns here. :)
