### ISSUE TITLE
Class reference tables have excess whitespace

### ISSUE THREAD

**Issue by jmuzina** [canonical/vanilla-framework#5238]
The class reference tables on documentation pages (e.g., [notification](https://vanillaframework.io/docs/patterns/notification#class-reference)), have an odd amount of whitespace to their right that is wasted space on the medium & large breakpoints.

![image](https://github.com/user-attachments/assets/f2277742-15e9-48c7-9cd0-e417a49f27f4)

Their usage of [grid](https://vanillaframework.io/docs/patterns/grid) should be checked and adjusted to make sure the table makes optimal use of available space.

**Comment by bartaz** [comment]
@jmuzina it's based on old designs. Let's just use the current 25-75 split approach and ask forgiveness later ;)
