### ISSUE TITLE
Implement rendering Jinja templates in example code snippets

### ISSUE THREAD

**Issue by jmuzina** [canonical/vanilla-framework#5254]
For our patterns and components that use macros (such as #5248 and #5212), we would like to some day give our users the opportunity to use our components with Jinja macros rather than plain HTML. Our [current implementation](https://github.com/canonical/vanilla-framework/blob/45005d16d080fadd71ea8e5a79bc047715bf1a71/templates/static/js/example.js#L41-L55) of example code snippets does not allow for rendering Jinja template code, as it visits the example page, retrieves its body, and returns its HTML as-rendered, making it impossible to show Jinja template code.

We need to find a way to render Jinja template code in our examples. Then we can allow the user to switch between rendered HTML & Jinja template in the code snippet for examples that support this.

**Comment by bartaz** [comment]
I believe this is already in progress. So triaging as part of current codebase.

**Comment by jmuzina** [comment]
Closing as completed in #5321
