### ISSUE TITLE
Search & Filter hidden Search button breaks vertical alignment within search box when focused

### ISSUE THREAD

**Issue by pastelcyborg** [canonical/vanilla-framework#5289]
**Describe the bug**

The Search & Filter search box contains a hidden Search button that becomes visible when the user tabs over to it from the chips/input itself. When this button becomes visible, it breaks vertical alignment within the search box, effectively pushing all the search box contents down a significant amount.

**To Reproduce**

1. Go to a [Search & Filter demo](https://vanillaframework.io/docs/examples/patterns/search-and-filter/chip-overflow)
2. Tab through the chips/input using the keyboard
3. Focus on the hidden Search button
4. Witness incorrect vertical alignment within the search box

**Expected behavior**

Optimally, the vertical size and alignment within the search box should not change when the hidden Search button is visible/focused.

**Screenshots**

![image](https://github.com/user-attachments/assets/be0364a9-5a4a-4d7c-a616-f8dd33526fd5)

**Comment by jmuzina** [comment]
The problem is that the form element containing the search input and the hidden search button takes up too much height when the hidden search input is focused. I attempted to solve this by restricting the height of these elements to `100%` in PR #5339 .

**Comment by bartaz** [comment]
Triage: this may be high effort fix. This component is used only in React component context, so we should check how it behaves there (not just in static Vanilla docs).

**Comment by bartaz** [comment]
Josh: possibly it can be a quick fix (just to make it not break it). Let's timebox them.

Triage: let's try to find a quick fix (max half-day worth of work). If not, leave it for new architecture.
