### ISSUE TITLE
Add support for chip links

### ISSUE THREAD

**Issue by juanruitina** [canonical/vanilla-framework#5317]
**Describe the bug**

[Chip](https://vanillaframework.io/docs/patterns/chip) styles don't work great when `p-chip` is applied to an `a` element instead of a button. I'd expect the same hover styles than the button: that means slightly darker background and no underline.

**To Reproduce**

1. Go to https://vanillaframework.io/docs/patterns/chip
2. Turn any chip into an `a` element
3. Hover

**Expected behavior**

No styling difference between links and buttons

**Screenshots**

![Screenshot 2024-08-21 at 17 07 47](https://github.com/user-attachments/assets/5207a8f2-5a63-45e4-a771-d458139d50ff)

**Comment by bartaz** [comment]
This is already in progress, and should be a low effort fix. Triaging for current codebase.
