### ISSUE TITLE
Add status label within documentation, not just navigation

### ISSUE THREAD

**Issue by petesfrench** [canonical/vanilla-framework#5349]
**Describe the bug**
I realize this isn't a bug, but didn't know where else to file it.

In the side navigation there are visual indicators as to where new features exists. However there is no information in the documentation about which specific feature is new. You can of course look in the changelog, but then what is the point of the status label to begin with.

**To Reproduce**

- Go to https://vanillaframework.io/docs/patterns/equal-height-row for example
- Notice in the side-navigation there is a green label that says 'new'
- Try to find the corresponding new component without prior knowledge or leaving the page

**Expected behavior**

A clear indication as to what is new, updated, deprecated etc

**Screenshots**

How it currently is (no indication that the wrapped class is new):
![image](https://github.com/user-attachments/assets/501ccf40-b959-43a9-984a-9ad3bf3f19ab)

How I think it should look (with some kind of visual indicator):
![image](https://github.com/user-attachments/assets/56aa51c2-5ec3-49a2-a7f8-85eca8b53606)

**Comment by petesfrench** [comment]
Also, I link to the relevant example would be nice to have in the docs

**Comment by bartaz** [comment]
We can have a quick fix (and manually manage those) in current docs.
But it's something to consider for future as well, how new architecture and documentation can make managing this easier.
