### ISSUE TITLE
Weirdness around fluid breakouts without an aside block

### ISSUE THREAD

**Issue by apollo13** [canonical/vanilla-framework#5366]
**Describe the bug**

I am not sure how to clearly describe this but I will try my best. As far as the bug is concerned, I think that the fluid breakout without an aside keeps the empty space for the aside to long while the grid already collapses.

**To Reproduce**

1. Download [index.txt](https://github.com/user-attachments/files/17235574/index.txt), save as index.html and view in a browser.
2. With a large screen it looks like this (this is correct as far as I understand the docs):
![image](https://github.com/user-attachments/assets/ac6e0269-7af1-4419-a7a2-1ce61a4bfa23)
3. Reduce the width of the screen till the grid column no longer has any outside margin (that is once it reaches grid-max-width):
![image](https://github.com/user-attachments/assets/dd09dc01-33d6-4f68-9233-61f43b3eacad)
4. At this point I feel like the fluid breakout with no aside should take the full width. Like it does when the aside is put above (by further decreasing the width):
![image](https://github.com/user-attachments/assets/e87f43c1-eb24-4e4d-baff-f90faad5830d)

**Desktop (please complete the following information):**

- OS: Fedora 40
- Browser Firefox 
- Version 130

**Comment by bartaz** [comment]
As far as I remember this works as expected. As long as there is enough space, the aside is on the left of the main container. And the "no-aside" version is aligned with the main container of the version with aside so that elements placed there can be properly aligned between those.

Like in this example:
<img width="1005" alt="image" src="https://github.com/user-attachments/assets/73381cc6-fde3-4cd0-bc37-ce7882f3bbfd">

https://vanillaframework.io/docs/examples/layouts/fluid-breakout/fluid-breakout-cards-with-aside-and-toolbar?theme=light

This particular layout is quite a legacy one, and not really used in our fresh designs. We are probably not going to maintain it, and would should likely mark it as deprecated.

**Comment by apollo13** [comment]
Ah, that makes sense. I guess it just felt weird because the idea of the fluid breakout was (at least for me) to shove in a table with a lot of data and when it then has less space than the grid it feels odd (will switch to full-width I think).

> This particular layout is quite a legacy one, and not really used in our fresh designs. We are probably not going to maintain it, and would should likely mark it as deprecated.

Which one exactly? Do you mean the whole fluid-breakout is going away? Just asking that I don't do something new with something that will get deprecated soon. What would you recommend for a table heavy site where I need as much screen space for the table as possible.

**Comment by bartaz** [comment]
I think tables were not the main use case for us, but cards like in the example above, so on smaller screens we could still keep the aside while having less cards in each row.

Yes, the whole fluid breakout is likely to be depracated. It doesn't mean it's "going away" anytime soon, it's just that we don't recommend using it on new projects and will likely be removed in future major release (but it's also not something we plan to do anytime soon). We are actually starting to plan and investigate moving our design system to new architecture, but that's still in a long term plans before we will be able to replace the current version.

Internally we stepped away from using it. We either use standard grid for websites (even "table heavy" like [Ubuntu CVEs](https://ubuntu.com/security/cves?version=noble&version=jammy&version=focal&version=bionic&version=xenial&version=trusty)) or [application layout](https://vanillaframework.io/docs/layouts/application) for apps that are more interactive (less website-like).

Although the application layout is mostly used via our React components, so the overall support via Vanilla SCSS library is quite basic and limited.

**Comment by bartaz** [comment]
Thanks for reaching out @apollo13. As this layout works as expected at the moment, I'm going to close this issue, but feel free to reach out if you have any more questions.
