### ISSUE TITLE
"Downloads" section is poorly laid out on medium screens

### ISSUE THREAD

**Issue by jmuzina** [canonical/vanilla-framework#5367]
**Describe the bug**

On medium screen sizes, the "Downloads" section on the home page makes poor usage of space, causing some overflow inside the cards. Maybe these cards should be stacked beneath "Downloads" on medium?

**To Reproduce**

1. Go to the [Vanilla homepage](https://vanillaframework.io/).
2. Reduce screen size to the lower end of the medium breakpoint (around 620px)
3. Observe the downloads section

**Expected behavior**

The downloads cards should not overflow. 

**Screenshots**
<img width="611" alt="Screenshot 2024-10-02 at 4 38 34 PM" src="https://github.com/user-attachments/assets/eb9fbf8f-9029-4c32-a4b1-a363af50e4ce">

**Context**
These are currently laid out using a 33/66 grid on medium.

**Comment by bartaz** [comment]
Let's just wrap it under the heading and have 50/50 split for cards?

**Comment by bartaz** [comment]
Or, if relevant use some of the new patterns? Would tiered list work here?
