### ISSUE TITLE
Support "currentColor" in vf-url-friendly-color

### ISSUE THREAD

**Issue by apollo13** [canonical/vanilla-framework#5382]
I am trying to reuse and color the icons provided by vanilla framework (in my case I am trying to color the icon from a link):
![image](https://github.com/user-attachments/assets/3434a33a-3583-4d14-a353-00bb17f93341)

For this I am currently having code like:
```
.p-icon--external-link--colored {
    @extend %icon;
    background-color: var(--vf-color-link-default);
    mask: vf-icon-external-link-url(currentColor);

    a:visited & {
        background-color: var(--vf-color-link-visited);
    }
}
```

but it throws the warning "currentColor is not a color.".

If I adjust ` vf-url-friendly-color` like this:
```
// This is to get the color variable inserted in an inline svg,
// we have to strip the `#` and replace with %23 for #HEX notation, or
// remove spaces and replace `,` with %2C for rgba() notation.
@function vf-url-friendly-color($color) {
  @if type-of($color) != 'color' {
    @if $color != 'currentColor' {
        @warn '#{$color} is not a color.';
    }
    @return $color;
  } @else {
    @return str-replace(str-replace(str-replace('#{$color}', '#', '%23'), ',', '%2C'), ' ');
  }
}
```
everything is fine. Would you be open to a PR supporting `currentColor`? If yes I could send one.

**Comment by bartaz** [comment]
Thanks @apollo13, we did consider CSS masks for icons, but they didn't work out of the box for all our icons.

I'm still curious how it may play out. So feel free to open a PR. 

We are in the process of starting new architecture of the design system, so I'm not sure how much time we will want to invest into updating current codebase to support this new way of handling icons, but it doesn't hurt to explore some options.

**Comment by apollo13** [comment]
Hi @bartaz, just to be clear my PR would only add support for `currentColor` to `vf-url-friendly-color` to allow easier customization of the icons for me. It wouldn't touch the icons itself because as you said that would require way more work and would not necessarily fit into the current architecture.

I am also not sure masks are a good solution, but the only thing I could come up with in the short-term. I kinda dislike the fact that I have to use the background-color and cannot just inherit the foreground color.

**Comment by bartaz** [comment]
That's fair @apollo13 and will definitely make the PR easier to review and approve!

**Comment by bartaz** [comment]
@apollo13 BTW, I just checked (as your suggestion of using `currentColor` ringed a bell), and you don't really need currentColor to use icon as mask.

Mask doesn't care about color of the svg used for mask. So you can use "black" mask and set background color to current color. At least that seems to have worked for me (when I checked quickly in the browser).

```
    background-color: currentColor;
    mask: vf-icon-external-link-url(#000);
```

**Comment by apollo13** [comment]
@bartaz True enough, shows how little I know about CSS. Thank you for your help!
