### ISSUE TITLE
Small button lacks side padding when using icons

### ISSUE THREAD

**Issue by JanOstrowka** [canonical/vanilla-framework#5386]
**Describe the bug**

The `small` variant of the button component lacks side padding when an icon (either start or trailing) is added. This results in insufficient spacing between the icon and the button's edge
![image](https://github.com/user-attachments/assets/f866b7c2-fed5-417c-bc5b-ce8c8c1de3f6)

---

**To reproduce**
Preview the example on [codepen.io](https://codepen.io/janostrowka/pen/OJKWVrq?editors=1000)

---

**Expected behavior**
The `small` variant button should have adequate side padding between the icon and the button's edge, similar to other button sizes.
![image](https://github.com/user-attachments/assets/4ce76248-ea29-4497-b9b4-774d93df7ec6)

**Comment by mrunalichiban111** [comment]
please assign this to me.

**Comment by bartaz** [comment]
Thanks for interest @mrunalichiban111 but this was just recently fixed. Not sure why GH didn't close it automatically.

Fixed by #5387
