### ISSUE TITLE
Quote wrapper import typo

### ISSUE THREAD

**Issue by britneywwc** [canonical/vanilla-framework#5421]
**Describe the bug**

The import for quote wrapper pattern should be changed from 
`{% from "_macros/vf_quote-wrapper.jinja" import vf_quote-wrapper %}` to 
`{% from "_macros/vf_quote-wrapper.jinja" import vf_quote_wrapper %}`

**To Reproduce**

1. Go to https://vanillaframework.io/docs/patterns/quote-wrapper#import
2. See typo on import
3. When trying to import with this, Jinja throws an error

**Expected behavior**

Imports quote wrapper vanilla quote patern as expected

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bartaz** [comment]
Fixed in #5422
