### ISSUE TITLE
Quote wrapper heading is not semantic 

### ISSUE THREAD

**Issue by mtruj013** [canonical/vanilla-framework#5426]
## Component/pattern to amend

The "title_text" in the [quote wrapper pattern](https://vanillaframework.io/docs/patterns/quote-wrapper) is a p element rather than a heading. I'm not sure if it was intentionally done this way for use cases where this _shouldn't_ be a heading semantically, but if so maybe there could be an additional flag implemented wherein users can set which element they'd like to use. 

## Context

In what context does your amendment solve a problem?:

Sections where the "title_text" is supposed to be a semantic heading

**Comment by jmuzina** [comment]
I think I agree that the title text should always be a semantic heading. I don't see a case where it shouldn't be one.

The interesting question is, what heading level should it use, and should that heading level be set by the pattern itself or by the developer who invokes the pattern? Currently the quote text itself is an h2, h4, or h6 depending on input (to accomodate quotes of various lengths). 

The title should probably always be a higher heading level than the quote text, though making the title an h1 in the case of the quote text being h2 is the only case I'm not sure about.

**Comment by mtruj013** [comment]
> The title should probably always be a higher heading level than the quote text, though making the title an h1 in the case of the quote text being h2 is the only case I'm not sure about.

Unless I'm misunderstanding how the pattern works, isn't the quote always a p element albeit with different styling? If so, that wouldn't cause an issue with ranking 

> what heading level should it use

If it helps, this is an h2 for sites 99.9% of the time 🙂

**Comment by jmuzina** [comment]
@mtruj013 

> Unless I'm misunderstanding how the pattern works, isn't the quote always a p element albeit with different styling? If so, that wouldn't cause an issue with ranking

Ah, good point. That should be fine then

> If it helps, this is an h2 for sites 99.9% of the time 🙂

We can make it a `h2` by default, what are some cases where it should not be an h2? Any opinions on if the heading level should be exposed as a parameter, so the user can set it themselves?

**Comment by bartaz** [comment]
I'd say don't expose it until it's needed.

It's easier to add things to API than to remove.
