### ISSUE TITLE
why did we change the grid? and column names?

### ISSUE THREAD

**Issue by pmahnke** [canonical/vanilla-framework#703]
this makes it hard to upgrade for sites using < v.1

the gird isn't using flex, the only thing we have been written up for, why change?

**Comment by barrymcgee** [comment]
There were a few reasons for this change:

- The previous grid was generated with Gridinator which by it's own admission suffered from rounding errors. This meant that layouts broke at certain resolutions.
- The vast majority of grid systems use the naming convention "col-*" where `*` is the number of columns whereas our previous grid used a rather clumsy `word-col` naming convention.
- Flexbox is no longer recommended for page layout, see [1]
- `v1` uses Shelves grid [2] wholesale which means that we can treat it as an external dep and upgrade it in the future if appropriate
- Swapping out column names should be a simple find and replace?

[1] https://jakearchibald.com/2014/dont-use-flexbox-for-page-layout/
[2] http://shelvesgrid.org/
